#include "VulkanConversions.h"
#include <unordered_map>

namespace bl {

uint32_t VulkanConversions::GetFormatSize(VkFormat format)
{
    switch (format) {
    case VK_FORMAT_UNDEFINED:
        return 0;
    case VK_FORMAT_R4G4_UNORM_PACK8:
        return 1;
    case VK_FORMAT_R4G4B4A4_UNORM_PACK16:
        return 2;
    case VK_FORMAT_B4G4R4A4_UNORM_PACK16:
        return 2;
    case VK_FORMAT_R5G6B5_UNORM_PACK16:
        return 2;
    case VK_FORMAT_B5G6R5_UNORM_PACK16:
        return 2;
    case VK_FORMAT_R5G5B5A1_UNORM_PACK16:
        return 2;
    case VK_FORMAT_B5G5R5A1_UNORM_PACK16:
        return 2;
    case VK_FORMAT_A1R5G5B5_UNORM_PACK16:
        return 2;
    case VK_FORMAT_R8_UNORM:
        return 1;
    case VK_FORMAT_R8_SNORM:
        return 1;
    case VK_FORMAT_R8_USCALED:
        return 1;
    case VK_FORMAT_R8_SSCALED:
        return 1;
    case VK_FORMAT_R8_UINT:
        return 1;
    case VK_FORMAT_R8_SINT:
        return 1;
    case VK_FORMAT_R8_SRGB:
        return 1;
    case VK_FORMAT_R8G8_UNORM:
        return 2;
    case VK_FORMAT_R8G8_SNORM:
        return 2;
    case VK_FORMAT_R8G8_USCALED:
        return 2;
    case VK_FORMAT_R8G8_SSCALED:
        return 2;
    case VK_FORMAT_R8G8_UINT:
        return 2;
    case VK_FORMAT_R8G8_SINT:
        return 2;
    case VK_FORMAT_R8G8_SRGB:
        return 2;
    case VK_FORMAT_R8G8B8_UNORM:
        return 3;
    case VK_FORMAT_R8G8B8_SNORM:
        return 3;
    case VK_FORMAT_R8G8B8_USCALED:
        return 3;
    case VK_FORMAT_R8G8B8_SSCALED:
        return 3;
    case VK_FORMAT_R8G8B8_UINT:
        return 3;
    case VK_FORMAT_R8G8B8_SINT:
        return 3;
    case VK_FORMAT_R8G8B8_SRGB:
        return 3;
    case VK_FORMAT_B8G8R8_UNORM:
        return 3;
    case VK_FORMAT_B8G8R8_SNORM:
        return 3;
    case VK_FORMAT_B8G8R8_USCALED:
        return 3;
    case VK_FORMAT_B8G8R8_SSCALED:
        return 3;
    case VK_FORMAT_B8G8R8_UINT:
        return 3;
    case VK_FORMAT_B8G8R8_SINT:
        return 3;
    case VK_FORMAT_B8G8R8_SRGB:
        return 3;
    case VK_FORMAT_R8G8B8A8_UNORM:
        return 4;
    case VK_FORMAT_R8G8B8A8_SNORM:
        return 4;
    case VK_FORMAT_R8G8B8A8_USCALED:
        return 4;
    case VK_FORMAT_R8G8B8A8_SSCALED:
        return 4;
    case VK_FORMAT_R8G8B8A8_UINT:
        return 4;
    case VK_FORMAT_R8G8B8A8_SINT:
        return 4;
    case VK_FORMAT_R8G8B8A8_SRGB:
        return 4;
    case VK_FORMAT_B8G8R8A8_UNORM:
        return 4;
    case VK_FORMAT_B8G8R8A8_SNORM:
        return 4;
    case VK_FORMAT_B8G8R8A8_USCALED:
        return 4;
    case VK_FORMAT_B8G8R8A8_SSCALED:
        return 4;
    case VK_FORMAT_B8G8R8A8_UINT:
        return 4;
    case VK_FORMAT_B8G8R8A8_SINT:
        return 4;
    case VK_FORMAT_B8G8R8A8_SRGB:
        return 4;
    case VK_FORMAT_A8B8G8R8_UNORM_PACK32:
        return 4;
    case VK_FORMAT_A8B8G8R8_SNORM_PACK32:
        return 4;
    case VK_FORMAT_A8B8G8R8_USCALED_PACK32:
        return 4;
    case VK_FORMAT_A8B8G8R8_SSCALED_PACK32:
        return 4;
    case VK_FORMAT_A8B8G8R8_UINT_PACK32:
        return 4;
    case VK_FORMAT_A8B8G8R8_SINT_PACK32:
        return 4;
    case VK_FORMAT_A8B8G8R8_SRGB_PACK32:
        return 4;
    case VK_FORMAT_A2R10G10B10_UNORM_PACK32:
        return 4;
    case VK_FORMAT_A2R10G10B10_SNORM_PACK32:
        return 4;
    case VK_FORMAT_A2R10G10B10_USCALED_PACK32:
        return 4;
    case VK_FORMAT_A2R10G10B10_SSCALED_PACK32:
        return 4;
    case VK_FORMAT_A2R10G10B10_UINT_PACK32:
        return 4;
    case VK_FORMAT_A2R10G10B10_SINT_PACK32:
        return 4;
    case VK_FORMAT_A2B10G10R10_UNORM_PACK32:
        return 4;
    case VK_FORMAT_A2B10G10R10_SNORM_PACK32:
        return 4;
    case VK_FORMAT_A2B10G10R10_USCALED_PACK32:
        return 4;
    case VK_FORMAT_A2B10G10R10_SSCALED_PACK32:
        return 4;
    case VK_FORMAT_A2B10G10R10_UINT_PACK32:
        return 4;
    case VK_FORMAT_A2B10G10R10_SINT_PACK32:
        return 4;
    case VK_FORMAT_R16_UNORM:
        return 2;
    case VK_FORMAT_R16_SNORM:
        return 2;
    case VK_FORMAT_R16_USCALED:
        return 2;
    case VK_FORMAT_R16_SSCALED:
        return 2;
    case VK_FORMAT_R16_UINT:
        return 2;
    case VK_FORMAT_R16_SINT:
        return 2;
    case VK_FORMAT_R16_SFLOAT:
        return 2;
    case VK_FORMAT_R16G16_UNORM:
        return 4;
    case VK_FORMAT_R16G16_SNORM:
        return 4;
    case VK_FORMAT_R16G16_USCALED:
        return 4;
    case VK_FORMAT_R16G16_SSCALED:
        return 4;
    case VK_FORMAT_R16G16_UINT:
        return 4;
    case VK_FORMAT_R16G16_SINT:
        return 4;
    case VK_FORMAT_R16G16_SFLOAT:
        return 4;
    case VK_FORMAT_R16G16B16_UNORM:
        return 6;
    case VK_FORMAT_R16G16B16_SNORM:
        return 6;
    case VK_FORMAT_R16G16B16_USCALED:
        return 6;
    case VK_FORMAT_R16G16B16_SSCALED:
        return 6;
    case VK_FORMAT_R16G16B16_UINT:
        return 6;
    case VK_FORMAT_R16G16B16_SINT:
        return 6;
    case VK_FORMAT_R16G16B16_SFLOAT:
        return 6;
    case VK_FORMAT_R16G16B16A16_UNORM:
        return 8;
    case VK_FORMAT_R16G16B16A16_SNORM:
        return 8;
    case VK_FORMAT_R16G16B16A16_USCALED:
        return 8;
    case VK_FORMAT_R16G16B16A16_SSCALED:
        return 8;
    case VK_FORMAT_R16G16B16A16_UINT:
        return 8;
    case VK_FORMAT_R16G16B16A16_SINT:
        return 8;
    case VK_FORMAT_R16G16B16A16_SFLOAT:
        return 8;
    case VK_FORMAT_R32_UINT:
        return 4;
    case VK_FORMAT_R32_SINT:
        return 4;
    case VK_FORMAT_R32_SFLOAT:
        return 4;
    case VK_FORMAT_R32G32_UINT:
        return 8;
    case VK_FORMAT_R32G32_SINT:
        return 8;
    case VK_FORMAT_R32G32_SFLOAT:
        return 8;
    case VK_FORMAT_R32G32B32_UINT:
        return 12;
    case VK_FORMAT_R32G32B32_SINT:
        return 12;
    case VK_FORMAT_R32G32B32_SFLOAT:
        return 12;
    case VK_FORMAT_R32G32B32A32_UINT:
        return 16;
    case VK_FORMAT_R32G32B32A32_SINT:
        return 16;
    case VK_FORMAT_R32G32B32A32_SFLOAT:
        return 16;
    case VK_FORMAT_R64_UINT:
        return 8;
    case VK_FORMAT_R64_SINT:
        return 8;
    case VK_FORMAT_R64_SFLOAT:
        return 8;
    case VK_FORMAT_R64G64_UINT:
        return 16;
    case VK_FORMAT_R64G64_SINT:
        return 16;
    case VK_FORMAT_R64G64_SFLOAT:
        return 16;
    case VK_FORMAT_R64G64B64_UINT:
        return 24;
    case VK_FORMAT_R64G64B64_SINT:
        return 24;
    case VK_FORMAT_R64G64B64_SFLOAT:
        return 24;
    case VK_FORMAT_R64G64B64A64_UINT:
        return 32;
    case VK_FORMAT_R64G64B64A64_SINT:
        return 32;
    case VK_FORMAT_R64G64B64A64_SFLOAT:
        return 32;
    case VK_FORMAT_B10G11R11_UFLOAT_PACK32:
        return 4;
    case VK_FORMAT_E5B9G9R9_UFLOAT_PACK32:
        return 4;
    default:
        throw std::runtime_error("Unimplemented vulkan format!");
    }
}

VkFormat VulkanConversions::VkFormatFromString(const std::string& format, VkFormat def)
{
    static std::unordered_map<std::string_view, VkFormat> convertMap = {
        { "VK_FORMAT_UNDEFINED", VK_FORMAT_UNDEFINED },
        { "VK_FORMAT_R4G4_UNORM_PACK8", VK_FORMAT_R4G4_UNORM_PACK8 },
        { "VK_FORMAT_R4G4B4A4_UNORM_PACK16", VK_FORMAT_R4G4B4A4_UNORM_PACK16 },
        { "VK_FORMAT_B4G4R4A4_UNORM_PACK16", VK_FORMAT_B4G4R4A4_UNORM_PACK16 },
        { "VK_FORMAT_R5G6B5_UNORM_PACK16", VK_FORMAT_R5G6B5_UNORM_PACK16 },
        { "VK_FORMAT_B5G6R5_UNORM_PACK16", VK_FORMAT_B5G6R5_UNORM_PACK16 },
        { "VK_FORMAT_R5G5B5A1_UNORM_PACK16", VK_FORMAT_R5G5B5A1_UNORM_PACK16 },
        { "VK_FORMAT_B5G5R5A1_UNORM_PACK16", VK_FORMAT_B5G5R5A1_UNORM_PACK16 },
        { "VK_FORMAT_A1R5G5B5_UNORM_PACK16", VK_FORMAT_A1R5G5B5_UNORM_PACK16 },
        { "VK_FORMAT_R8_UNORM", VK_FORMAT_R8_UNORM },
        { "VK_FORMAT_R8_SNORM", VK_FORMAT_R8_SNORM },
        { "VK_FORMAT_R8_USCALED", VK_FORMAT_R8_USCALED },
        { "VK_FORMAT_R8_SSCALED", VK_FORMAT_R8_SSCALED },
        { "VK_FORMAT_R8_UINT", VK_FORMAT_R8_UINT },
        { "VK_FORMAT_R8_SINT", VK_FORMAT_R8_SINT },
        { "VK_FORMAT_R8_SRGB", VK_FORMAT_R8_SRGB },
        { "VK_FORMAT_R8G8_UNORM", VK_FORMAT_R8G8_UNORM },
        { "VK_FORMAT_R8G8_SNORM", VK_FORMAT_R8G8_SNORM },
        { "VK_FORMAT_R8G8_USCALED", VK_FORMAT_R8G8_USCALED },
        { "VK_FORMAT_R8G8_SSCALED", VK_FORMAT_R8G8_SSCALED },
        { "VK_FORMAT_R8G8_UINT", VK_FORMAT_R8G8_UINT },
        { "VK_FORMAT_R8G8_SINT", VK_FORMAT_R8G8_SINT },
        { "VK_FORMAT_R8G8_SRGB", VK_FORMAT_R8G8_SRGB },
        { "VK_FORMAT_R8G8B8_UNORM", VK_FORMAT_R8G8B8_UNORM },
        { "VK_FORMAT_R8G8B8_SNORM", VK_FORMAT_R8G8B8_SNORM },
        { "VK_FORMAT_R8G8B8_USCALED", VK_FORMAT_R8G8B8_USCALED },
        { "VK_FORMAT_R8G8B8_SSCALED", VK_FORMAT_R8G8B8_SSCALED },
        { "VK_FORMAT_R8G8B8_UINT", VK_FORMAT_R8G8B8_UINT },
        { "VK_FORMAT_R8G8B8_SINT", VK_FORMAT_R8G8B8_SINT },
        { "VK_FORMAT_R8G8B8_SRGB", VK_FORMAT_R8G8B8_SRGB },
        { "VK_FORMAT_B8G8R8_UNORM", VK_FORMAT_B8G8R8_UNORM },
        { "VK_FORMAT_B8G8R8_SNORM", VK_FORMAT_B8G8R8_SNORM },
        { "VK_FORMAT_B8G8R8_USCALED", VK_FORMAT_B8G8R8_USCALED },
        { "VK_FORMAT_B8G8R8_SSCALED", VK_FORMAT_B8G8R8_SSCALED },
        { "VK_FORMAT_B8G8R8_UINT", VK_FORMAT_B8G8R8_UINT },
        { "VK_FORMAT_B8G8R8_SINT", VK_FORMAT_B8G8R8_SINT },
        { "VK_FORMAT_B8G8R8_SRGB", VK_FORMAT_B8G8R8_SRGB },
        { "VK_FORMAT_R8G8B8A8_UNORM", VK_FORMAT_R8G8B8A8_UNORM },
        { "VK_FORMAT_R8G8B8A8_SNORM", VK_FORMAT_R8G8B8A8_SNORM },
        { "VK_FORMAT_R8G8B8A8_USCALED", VK_FORMAT_R8G8B8A8_USCALED },
        { "VK_FORMAT_R8G8B8A8_SSCALED", VK_FORMAT_R8G8B8A8_SSCALED },
        { "VK_FORMAT_R8G8B8A8_UINT", VK_FORMAT_R8G8B8A8_UINT },
        { "VK_FORMAT_R8G8B8A8_SINT", VK_FORMAT_R8G8B8A8_SINT },
        { "VK_FORMAT_R8G8B8A8_SRGB", VK_FORMAT_R8G8B8A8_SRGB },
        { "VK_FORMAT_B8G8R8A8_UNORM", VK_FORMAT_B8G8R8A8_UNORM },
        { "VK_FORMAT_B8G8R8A8_SNORM", VK_FORMAT_B8G8R8A8_SNORM },
        { "VK_FORMAT_B8G8R8A8_USCALED", VK_FORMAT_B8G8R8A8_USCALED },
        { "VK_FORMAT_B8G8R8A8_SSCALED", VK_FORMAT_B8G8R8A8_SSCALED },
        { "VK_FORMAT_B8G8R8A8_UINT", VK_FORMAT_B8G8R8A8_UINT },
        { "VK_FORMAT_B8G8R8A8_SINT", VK_FORMAT_B8G8R8A8_SINT },
        { "VK_FORMAT_B8G8R8A8_SRGB", VK_FORMAT_B8G8R8A8_SRGB },
        { "VK_FORMAT_A8B8G8R8_UNORM_PACK32", VK_FORMAT_A8B8G8R8_UNORM_PACK32 },
        { "VK_FORMAT_A8B8G8R8_SNORM_PACK32", VK_FORMAT_A8B8G8R8_SNORM_PACK32 },
        { "VK_FORMAT_A8B8G8R8_USCALED_PACK32", VK_FORMAT_A8B8G8R8_USCALED_PACK32 },
        { "VK_FORMAT_A8B8G8R8_SSCALED_PACK32", VK_FORMAT_A8B8G8R8_SSCALED_PACK32 },
        { "VK_FORMAT_A8B8G8R8_UINT_PACK32", VK_FORMAT_A8B8G8R8_UINT_PACK32 },
        { "VK_FORMAT_A8B8G8R8_SINT_PACK32", VK_FORMAT_A8B8G8R8_SINT_PACK32 },
        { "VK_FORMAT_A8B8G8R8_SRGB_PACK32", VK_FORMAT_A8B8G8R8_SRGB_PACK32 },
        { "VK_FORMAT_A2R10G10B10_UNORM_PACK32", VK_FORMAT_A2R10G10B10_UNORM_PACK32 },
        { "VK_FORMAT_A2R10G10B10_SNORM_PACK32", VK_FORMAT_A2R10G10B10_SNORM_PACK32 },
        { "VK_FORMAT_A2R10G10B10_USCALED_PACK32", VK_FORMAT_A2R10G10B10_USCALED_PACK32 },
        { "VK_FORMAT_A2R10G10B10_SSCALED_PACK32", VK_FORMAT_A2R10G10B10_SSCALED_PACK32 },
        { "VK_FORMAT_A2R10G10B10_UINT_PACK32", VK_FORMAT_A2R10G10B10_UINT_PACK32 },
        { "VK_FORMAT_A2R10G10B10_SINT_PACK32", VK_FORMAT_A2R10G10B10_SINT_PACK32 },
        { "VK_FORMAT_A2B10G10R10_UNORM_PACK32", VK_FORMAT_A2B10G10R10_UNORM_PACK32 },
        { "VK_FORMAT_A2B10G10R10_SNORM_PACK32", VK_FORMAT_A2B10G10R10_SNORM_PACK32 },
        { "VK_FORMAT_A2B10G10R10_USCALED_PACK32", VK_FORMAT_A2B10G10R10_USCALED_PACK32 },
        { "VK_FORMAT_A2B10G10R10_SSCALED_PACK32", VK_FORMAT_A2B10G10R10_SSCALED_PACK32 },
        { "VK_FORMAT_A2B10G10R10_UINT_PACK32", VK_FORMAT_A2B10G10R10_UINT_PACK32 },
        { "VK_FORMAT_A2B10G10R10_SINT_PACK32", VK_FORMAT_A2B10G10R10_SINT_PACK32 },
        { "VK_FORMAT_R16_UNORM", VK_FORMAT_R16_UNORM },
        { "VK_FORMAT_R16_SNORM", VK_FORMAT_R16_SNORM },
        { "VK_FORMAT_R16_USCALED", VK_FORMAT_R16_USCALED },
        { "VK_FORMAT_R16_SSCALED", VK_FORMAT_R16_SSCALED },
        { "VK_FORMAT_R16_UINT", VK_FORMAT_R16_UINT },
        { "VK_FORMAT_R16_SINT", VK_FORMAT_R16_SINT },
        { "VK_FORMAT_R16_SFLOAT", VK_FORMAT_R16_SFLOAT },
        { "VK_FORMAT_R16G16_UNORM", VK_FORMAT_R16G16_UNORM },
        { "VK_FORMAT_R16G16_SNORM", VK_FORMAT_R16G16_SNORM },
        { "VK_FORMAT_R16G16_USCALED", VK_FORMAT_R16G16_USCALED },
        { "VK_FORMAT_R16G16_SSCALED", VK_FORMAT_R16G16_SSCALED },
        { "VK_FORMAT_R16G16_UINT", VK_FORMAT_R16G16_UINT },
        { "VK_FORMAT_R16G16_SINT", VK_FORMAT_R16G16_SINT },
        { "VK_FORMAT_R16G16_SFLOAT", VK_FORMAT_R16G16_SFLOAT },
        { "VK_FORMAT_R16G16B16_UNORM", VK_FORMAT_R16G16B16_UNORM },
        { "VK_FORMAT_R16G16B16_SNORM", VK_FORMAT_R16G16B16_SNORM },
        { "VK_FORMAT_R16G16B16_USCALED", VK_FORMAT_R16G16B16_USCALED },
        { "VK_FORMAT_R16G16B16_SSCALED", VK_FORMAT_R16G16B16_SSCALED },
        { "VK_FORMAT_R16G16B16_UINT", VK_FORMAT_R16G16B16_UINT },
        { "VK_FORMAT_R16G16B16_SINT", VK_FORMAT_R16G16B16_SINT },
        { "VK_FORMAT_R16G16B16_SFLOAT", VK_FORMAT_R16G16B16_SFLOAT },
        { "VK_FORMAT_R16G16B16A16_UNORM", VK_FORMAT_R16G16B16A16_UNORM },
        { "VK_FORMAT_R16G16B16A16_SNORM", VK_FORMAT_R16G16B16A16_SNORM },
        { "VK_FORMAT_R16G16B16A16_USCALED", VK_FORMAT_R16G16B16A16_USCALED },
        { "VK_FORMAT_R16G16B16A16_SSCALED", VK_FORMAT_R16G16B16A16_SSCALED },
        { "VK_FORMAT_R16G16B16A16_UINT", VK_FORMAT_R16G16B16A16_UINT },
        { "VK_FORMAT_R16G16B16A16_SINT", VK_FORMAT_R16G16B16A16_SINT },
        { "VK_FORMAT_R16G16B16A16_SFLOAT", VK_FORMAT_R16G16B16A16_SFLOAT },
        { "VK_FORMAT_R32_UINT", VK_FORMAT_R32_UINT },
        { "VK_FORMAT_R32_SINT", VK_FORMAT_R32_SINT },
        { "VK_FORMAT_R32_SFLOAT", VK_FORMAT_R32_SFLOAT },
        { "VK_FORMAT_R32G32_UINT", VK_FORMAT_R32G32_UINT },
        { "VK_FORMAT_R32G32_SINT", VK_FORMAT_R32G32_SINT },
        { "VK_FORMAT_R32G32_SFLOAT", VK_FORMAT_R32G32_SFLOAT },
        { "VK_FORMAT_R32G32B32_UINT", VK_FORMAT_R32G32B32_UINT },
        { "VK_FORMAT_R32G32B32_SINT", VK_FORMAT_R32G32B32_SINT },
        { "VK_FORMAT_R32G32B32_SFLOAT", VK_FORMAT_R32G32B32_SFLOAT },
        { "VK_FORMAT_R32G32B32A32_UINT", VK_FORMAT_R32G32B32A32_UINT },
        { "VK_FORMAT_R32G32B32A32_SINT", VK_FORMAT_R32G32B32A32_SINT },
        { "VK_FORMAT_R32G32B32A32_SFLOAT", VK_FORMAT_R32G32B32A32_SFLOAT },
        { "VK_FORMAT_R64_UINT", VK_FORMAT_R64_UINT },
        { "VK_FORMAT_R64_SINT", VK_FORMAT_R64_SINT },
        { "VK_FORMAT_R64_SFLOAT", VK_FORMAT_R64_SFLOAT },
        { "VK_FORMAT_R64G64_UINT", VK_FORMAT_R64G64_UINT },
        { "VK_FORMAT_R64G64_SINT", VK_FORMAT_R64G64_SINT },
        { "VK_FORMAT_R64G64_SFLOAT", VK_FORMAT_R64G64_SFLOAT },
        { "VK_FORMAT_R64G64B64_UINT", VK_FORMAT_R64G64B64_UINT },
        { "VK_FORMAT_R64G64B64_SINT", VK_FORMAT_R64G64B64_SINT },
        { "VK_FORMAT_R64G64B64_SFLOAT", VK_FORMAT_R64G64B64_SFLOAT },
        { "VK_FORMAT_R64G64B64A64_UINT", VK_FORMAT_R64G64B64A64_UINT },
        { "VK_FORMAT_R64G64B64A64_SINT", VK_FORMAT_R64G64B64A64_SINT },
        { "VK_FORMAT_R64G64B64A64_SFLOAT", VK_FORMAT_R64G64B64A64_SFLOAT },
        { "VK_FORMAT_B10G11R11_UFLOAT_PACK32", VK_FORMAT_B10G11R11_UFLOAT_PACK32 },
        { "VK_FORMAT_E5B9G9R9_UFLOAT_PACK32", VK_FORMAT_E5B9G9R9_UFLOAT_PACK32 },
        { "VK_FORMAT_D16_UNORM", VK_FORMAT_D16_UNORM },
        { "VK_FORMAT_X8_D24_UNORM_PACK32", VK_FORMAT_X8_D24_UNORM_PACK32 },
        { "VK_FORMAT_D32_SFLOAT", VK_FORMAT_D32_SFLOAT },
        { "VK_FORMAT_S8_UINT", VK_FORMAT_S8_UINT },
        { "VK_FORMAT_D16_UNORM_S8_UINT", VK_FORMAT_D16_UNORM_S8_UINT },
        { "VK_FORMAT_D24_UNORM_S8_UINT", VK_FORMAT_D24_UNORM_S8_UINT },
        { "VK_FORMAT_D32_SFLOAT_S8_UINT", VK_FORMAT_D32_SFLOAT_S8_UINT },
        { "VK_FORMAT_BC1_RGB_UNORM_BLOCK", VK_FORMAT_BC1_RGB_UNORM_BLOCK },
        { "VK_FORMAT_BC1_RGB_SRGB_BLOCK", VK_FORMAT_BC1_RGB_SRGB_BLOCK },
        { "VK_FORMAT_BC1_RGBA_UNORM_BLOCK", VK_FORMAT_BC1_RGBA_UNORM_BLOCK },
        { "VK_FORMAT_BC1_RGBA_SRGB_BLOCK", VK_FORMAT_BC1_RGBA_SRGB_BLOCK },
        { "VK_FORMAT_BC2_UNORM_BLOCK", VK_FORMAT_BC2_UNORM_BLOCK },
        { "VK_FORMAT_BC2_SRGB_BLOCK", VK_FORMAT_BC2_SRGB_BLOCK },
        { "VK_FORMAT_BC3_UNORM_BLOCK", VK_FORMAT_BC3_UNORM_BLOCK },
        { "VK_FORMAT_BC3_SRGB_BLOCK", VK_FORMAT_BC3_SRGB_BLOCK },
        { "VK_FORMAT_BC4_UNORM_BLOCK", VK_FORMAT_BC4_UNORM_BLOCK },
        { "VK_FORMAT_BC4_SNORM_BLOCK", VK_FORMAT_BC4_SNORM_BLOCK },
        { "VK_FORMAT_BC5_UNORM_BLOCK", VK_FORMAT_BC5_UNORM_BLOCK },
        { "VK_FORMAT_BC5_SNORM_BLOCK", VK_FORMAT_BC5_SNORM_BLOCK },
        { "VK_FORMAT_BC6H_UFLOAT_BLOCK", VK_FORMAT_BC6H_UFLOAT_BLOCK },
        { "VK_FORMAT_BC6H_SFLOAT_BLOCK", VK_FORMAT_BC6H_SFLOAT_BLOCK },
        { "VK_FORMAT_BC7_UNORM_BLOCK", VK_FORMAT_BC7_UNORM_BLOCK },
        { "VK_FORMAT_BC7_SRGB_BLOCK", VK_FORMAT_BC7_SRGB_BLOCK },
        { "VK_FORMAT_ETC2_R8G8B8_UNORM_BLOCK", VK_FORMAT_ETC2_R8G8B8_UNORM_BLOCK },
        { "VK_FORMAT_ETC2_R8G8B8_SRGB_BLOCK", VK_FORMAT_ETC2_R8G8B8_SRGB_BLOCK },
        { "VK_FORMAT_ETC2_R8G8B8A1_UNORM_BLOCK", VK_FORMAT_ETC2_R8G8B8A1_UNORM_BLOCK },
        { "VK_FORMAT_ETC2_R8G8B8A1_SRGB_BLOCK", VK_FORMAT_ETC2_R8G8B8A1_SRGB_BLOCK },
        { "VK_FORMAT_ETC2_R8G8B8A8_UNORM_BLOCK", VK_FORMAT_ETC2_R8G8B8A8_UNORM_BLOCK },
        { "VK_FORMAT_ETC2_R8G8B8A8_SRGB_BLOCK", VK_FORMAT_ETC2_R8G8B8A8_SRGB_BLOCK },
        { "VK_FORMAT_EAC_R11_UNORM_BLOCK", VK_FORMAT_EAC_R11_UNORM_BLOCK },
        { "VK_FORMAT_EAC_R11_SNORM_BLOCK", VK_FORMAT_EAC_R11_SNORM_BLOCK },
        { "VK_FORMAT_EAC_R11G11_UNORM_BLOCK", VK_FORMAT_EAC_R11G11_UNORM_BLOCK },
        { "VK_FORMAT_EAC_R11G11_SNORM_BLOCK", VK_FORMAT_EAC_R11G11_SNORM_BLOCK },
        { "VK_FORMAT_ASTC_4x4_UNORM_BLOCK", VK_FORMAT_ASTC_4x4_UNORM_BLOCK },
        { "VK_FORMAT_ASTC_4x4_SRGB_BLOCK", VK_FORMAT_ASTC_4x4_SRGB_BLOCK },
        { "VK_FORMAT_ASTC_5x4_UNORM_BLOCK", VK_FORMAT_ASTC_5x4_UNORM_BLOCK },
        { "VK_FORMAT_ASTC_5x4_SRGB_BLOCK", VK_FORMAT_ASTC_5x4_SRGB_BLOCK },
        { "VK_FORMAT_ASTC_5x5_UNORM_BLOCK", VK_FORMAT_ASTC_5x5_UNORM_BLOCK },
        { "VK_FORMAT_ASTC_5x5_SRGB_BLOCK", VK_FORMAT_ASTC_5x5_SRGB_BLOCK },
        { "VK_FORMAT_ASTC_6x5_UNORM_BLOCK", VK_FORMAT_ASTC_6x5_UNORM_BLOCK },
        { "VK_FORMAT_ASTC_6x5_SRGB_BLOCK", VK_FORMAT_ASTC_6x5_SRGB_BLOCK },
        { "VK_FORMAT_ASTC_6x6_UNORM_BLOCK", VK_FORMAT_ASTC_6x6_UNORM_BLOCK },
        { "VK_FORMAT_ASTC_6x6_SRGB_BLOCK", VK_FORMAT_ASTC_6x6_SRGB_BLOCK },
        { "VK_FORMAT_ASTC_8x5_UNORM_BLOCK", VK_FORMAT_ASTC_8x5_UNORM_BLOCK },
        { "VK_FORMAT_ASTC_8x5_SRGB_BLOCK", VK_FORMAT_ASTC_8x5_SRGB_BLOCK },
        { "VK_FORMAT_ASTC_8x6_UNORM_BLOCK", VK_FORMAT_ASTC_8x6_UNORM_BLOCK },
        { "VK_FORMAT_ASTC_8x6_SRGB_BLOCK", VK_FORMAT_ASTC_8x6_SRGB_BLOCK },
        { "VK_FORMAT_ASTC_8x8_UNORM_BLOCK", VK_FORMAT_ASTC_8x8_UNORM_BLOCK },
        { "VK_FORMAT_ASTC_8x8_SRGB_BLOCK", VK_FORMAT_ASTC_8x8_SRGB_BLOCK },
        { "VK_FORMAT_ASTC_10x5_UNORM_BLOCK", VK_FORMAT_ASTC_10x5_UNORM_BLOCK },
        { "VK_FORMAT_ASTC_10x5_SRGB_BLOCK", VK_FORMAT_ASTC_10x5_SRGB_BLOCK },
        { "VK_FORMAT_ASTC_10x6_UNORM_BLOCK", VK_FORMAT_ASTC_10x6_UNORM_BLOCK },
        { "VK_FORMAT_ASTC_10x6_SRGB_BLOCK", VK_FORMAT_ASTC_10x6_SRGB_BLOCK },
        { "VK_FORMAT_ASTC_10x8_UNORM_BLOCK", VK_FORMAT_ASTC_10x8_UNORM_BLOCK },
        { "VK_FORMAT_ASTC_10x8_SRGB_BLOCK", VK_FORMAT_ASTC_10x8_SRGB_BLOCK },
        { "VK_FORMAT_ASTC_10x10_UNORM_BLOCK", VK_FORMAT_ASTC_10x10_UNORM_BLOCK },
        { "VK_FORMAT_ASTC_10x10_SRGB_BLOCK", VK_FORMAT_ASTC_10x10_SRGB_BLOCK },
        { "VK_FORMAT_ASTC_12x10_UNORM_BLOCK", VK_FORMAT_ASTC_12x10_UNORM_BLOCK },
        { "VK_FORMAT_ASTC_12x10_SRGB_BLOCK", VK_FORMAT_ASTC_12x10_SRGB_BLOCK },
        { "VK_FORMAT_ASTC_12x12_UNORM_BLOCK", VK_FORMAT_ASTC_12x12_UNORM_BLOCK },
        { "VK_FORMAT_ASTC_12x12_SRGB_BLOCK", VK_FORMAT_ASTC_12x12_SRGB_BLOCK },
        { "VK_FORMAT_G8B8G8R8_422_UNORM", VK_FORMAT_G8B8G8R8_422_UNORM },
        { "VK_FORMAT_B8G8R8G8_422_UNORM", VK_FORMAT_B8G8R8G8_422_UNORM },
        { "VK_FORMAT_G8_B8_R8_3PLANE_420_UNORM", VK_FORMAT_G8_B8_R8_3PLANE_420_UNORM },
        { "VK_FORMAT_G8_B8R8_2PLANE_420_UNORM", VK_FORMAT_G8_B8R8_2PLANE_420_UNORM },
        { "VK_FORMAT_G8_B8_R8_3PLANE_422_UNORM", VK_FORMAT_G8_B8_R8_3PLANE_422_UNORM },
        { "VK_FORMAT_G8_B8R8_2PLANE_422_UNORM", VK_FORMAT_G8_B8R8_2PLANE_422_UNORM },
        { "VK_FORMAT_G8_B8_R8_3PLANE_444_UNORM", VK_FORMAT_G8_B8_R8_3PLANE_444_UNORM },
        { "VK_FORMAT_R10X6_UNORM_PACK16", VK_FORMAT_R10X6_UNORM_PACK16 },
        { "VK_FORMAT_R10X6G10X6_UNORM_2PACK16", VK_FORMAT_R10X6G10X6_UNORM_2PACK16 },
        { "VK_FORMAT_R10X6G10X6B10X6A10X6_UNORM_4PACK16", VK_FORMAT_R10X6G10X6B10X6A10X6_UNORM_4PACK16 },
        { "VK_FORMAT_G10X6B10X6G10X6R10X6_422_UNORM_4PACK16", VK_FORMAT_G10X6B10X6G10X6R10X6_422_UNORM_4PACK16 },
        { "VK_FORMAT_B10X6G10X6R10X6G10X6_422_UNORM_4PACK16", VK_FORMAT_B10X6G10X6R10X6G10X6_422_UNORM_4PACK16 },
        { "VK_FORMAT_G10X6_B10X6_R10X6_3PLANE_420_UNORM_3PACK16", VK_FORMAT_G10X6_B10X6_R10X6_3PLANE_420_UNORM_3PACK16 },
        { "VK_FORMAT_G10X6_B10X6R10X6_2PLANE_420_UNORM_3PACK16", VK_FORMAT_G10X6_B10X6R10X6_2PLANE_420_UNORM_3PACK16 },
        { "VK_FORMAT_G10X6_B10X6_R10X6_3PLANE_422_UNORM_3PACK16", VK_FORMAT_G10X6_B10X6_R10X6_3PLANE_422_UNORM_3PACK16 },
        { "VK_FORMAT_G10X6_B10X6R10X6_2PLANE_422_UNORM_3PACK16", VK_FORMAT_G10X6_B10X6R10X6_2PLANE_422_UNORM_3PACK16 },
        { "VK_FORMAT_G10X6_B10X6_R10X6_3PLANE_444_UNORM_3PACK16", VK_FORMAT_G10X6_B10X6_R10X6_3PLANE_444_UNORM_3PACK16 },
        { "VK_FORMAT_R12X4_UNORM_PACK16", VK_FORMAT_R12X4_UNORM_PACK16 },
        { "VK_FORMAT_R12X4G12X4_UNORM_2PACK16", VK_FORMAT_R12X4G12X4_UNORM_2PACK16 },
        { "VK_FORMAT_R12X4G12X4B12X4A12X4_UNORM_4PACK16", VK_FORMAT_R12X4G12X4B12X4A12X4_UNORM_4PACK16 },
        { "VK_FORMAT_G12X4B12X4G12X4R12X4_422_UNORM_4PACK16", VK_FORMAT_G12X4B12X4G12X4R12X4_422_UNORM_4PACK16 },
        { "VK_FORMAT_B12X4G12X4R12X4G12X4_422_UNORM_4PACK16", VK_FORMAT_B12X4G12X4R12X4G12X4_422_UNORM_4PACK16 },
        { "VK_FORMAT_G12X4_B12X4_R12X4_3PLANE_420_UNORM_3PACK16", VK_FORMAT_G12X4_B12X4_R12X4_3PLANE_420_UNORM_3PACK16 },
        { "VK_FORMAT_G12X4_B12X4R12X4_2PLANE_420_UNORM_3PACK16", VK_FORMAT_G12X4_B12X4R12X4_2PLANE_420_UNORM_3PACK16 },
        { "VK_FORMAT_G12X4_B12X4_R12X4_3PLANE_422_UNORM_3PACK16", VK_FORMAT_G12X4_B12X4_R12X4_3PLANE_422_UNORM_3PACK16 },
        { "VK_FORMAT_G12X4_B12X4R12X4_2PLANE_422_UNORM_3PACK16", VK_FORMAT_G12X4_B12X4R12X4_2PLANE_422_UNORM_3PACK16 },
        { "VK_FORMAT_G12X4_B12X4_R12X4_3PLANE_444_UNORM_3PACK16", VK_FORMAT_G12X4_B12X4_R12X4_3PLANE_444_UNORM_3PACK16 },
        { "VK_FORMAT_G16B16G16R16_422_UNORM", VK_FORMAT_G16B16G16R16_422_UNORM },
        { "VK_FORMAT_B16G16R16G16_422_UNORM", VK_FORMAT_B16G16R16G16_422_UNORM },
        { "VK_FORMAT_G16_B16_R16_3PLANE_420_UNORM", VK_FORMAT_G16_B16_R16_3PLANE_420_UNORM },
        { "VK_FORMAT_G16_B16R16_2PLANE_420_UNORM", VK_FORMAT_G16_B16R16_2PLANE_420_UNORM },
        { "VK_FORMAT_G16_B16_R16_3PLANE_422_UNORM", VK_FORMAT_G16_B16_R16_3PLANE_422_UNORM },
        { "VK_FORMAT_G16_B16R16_2PLANE_422_UNORM", VK_FORMAT_G16_B16R16_2PLANE_422_UNORM },
        { "VK_FORMAT_G16_B16_R16_3PLANE_444_UNORM", VK_FORMAT_G16_B16_R16_3PLANE_444_UNORM },
        { "VK_FORMAT_G8_B8R8_2PLANE_444_UNORM", VK_FORMAT_G8_B8R8_2PLANE_444_UNORM },
        { "VK_FORMAT_G10X6_B10X6R10X6_2PLANE_444_UNORM_3PACK16", VK_FORMAT_G10X6_B10X6R10X6_2PLANE_444_UNORM_3PACK16 },
        { "VK_FORMAT_G12X4_B12X4R12X4_2PLANE_444_UNORM_3PACK16", VK_FORMAT_G12X4_B12X4R12X4_2PLANE_444_UNORM_3PACK16 },
        { "VK_FORMAT_G16_B16R16_2PLANE_444_UNORM", VK_FORMAT_G16_B16R16_2PLANE_444_UNORM },
        { "VK_FORMAT_A4R4G4B4_UNORM_PACK16", VK_FORMAT_A4R4G4B4_UNORM_PACK16 },
        { "VK_FORMAT_A4B4G4R4_UNORM_PACK16", VK_FORMAT_A4B4G4R4_UNORM_PACK16 },
        { "VK_FORMAT_ASTC_4x4_SFLOAT_BLOCK", VK_FORMAT_ASTC_4x4_SFLOAT_BLOCK },
        { "VK_FORMAT_ASTC_5x4_SFLOAT_BLOCK", VK_FORMAT_ASTC_5x4_SFLOAT_BLOCK },
        { "VK_FORMAT_ASTC_5x5_SFLOAT_BLOCK", VK_FORMAT_ASTC_5x5_SFLOAT_BLOCK },
        { "VK_FORMAT_ASTC_6x5_SFLOAT_BLOCK", VK_FORMAT_ASTC_6x5_SFLOAT_BLOCK },
        { "VK_FORMAT_ASTC_6x6_SFLOAT_BLOCK", VK_FORMAT_ASTC_6x6_SFLOAT_BLOCK },
        { "VK_FORMAT_ASTC_8x5_SFLOAT_BLOCK", VK_FORMAT_ASTC_8x5_SFLOAT_BLOCK },
        { "VK_FORMAT_ASTC_8x6_SFLOAT_BLOCK", VK_FORMAT_ASTC_8x6_SFLOAT_BLOCK },
        { "VK_FORMAT_ASTC_8x8_SFLOAT_BLOCK", VK_FORMAT_ASTC_8x8_SFLOAT_BLOCK },
        { "VK_FORMAT_ASTC_10x5_SFLOAT_BLOCK", VK_FORMAT_ASTC_10x5_SFLOAT_BLOCK },
        { "VK_FORMAT_ASTC_10x6_SFLOAT_BLOCK", VK_FORMAT_ASTC_10x6_SFLOAT_BLOCK },
        { "VK_FORMAT_ASTC_10x8_SFLOAT_BLOCK", VK_FORMAT_ASTC_10x8_SFLOAT_BLOCK },
        { "VK_FORMAT_ASTC_10x10_SFLOAT_BLOCK", VK_FORMAT_ASTC_10x10_SFLOAT_BLOCK },
        { "VK_FORMAT_ASTC_12x10_SFLOAT_BLOCK", VK_FORMAT_ASTC_12x10_SFLOAT_BLOCK },
        { "VK_FORMAT_ASTC_12x12_SFLOAT_BLOCK", VK_FORMAT_ASTC_12x12_SFLOAT_BLOCK },
        { "VK_FORMAT_PVRTC1_2BPP_UNORM_BLOCK_IMG", VK_FORMAT_PVRTC1_2BPP_UNORM_BLOCK_IMG },
        { "VK_FORMAT_PVRTC1_4BPP_UNORM_BLOCK_IMG", VK_FORMAT_PVRTC1_4BPP_UNORM_BLOCK_IMG },
        { "VK_FORMAT_PVRTC2_2BPP_UNORM_BLOCK_IMG", VK_FORMAT_PVRTC2_2BPP_UNORM_BLOCK_IMG },
        { "VK_FORMAT_PVRTC2_4BPP_UNORM_BLOCK_IMG", VK_FORMAT_PVRTC2_4BPP_UNORM_BLOCK_IMG },
        { "VK_FORMAT_PVRTC1_2BPP_SRGB_BLOCK_IMG", VK_FORMAT_PVRTC1_2BPP_SRGB_BLOCK_IMG },
        { "VK_FORMAT_PVRTC1_4BPP_SRGB_BLOCK_IMG", VK_FORMAT_PVRTC1_4BPP_SRGB_BLOCK_IMG },
        { "VK_FORMAT_PVRTC2_2BPP_SRGB_BLOCK_IMG", VK_FORMAT_PVRTC2_2BPP_SRGB_BLOCK_IMG },
        { "VK_FORMAT_PVRTC2_4BPP_SRGB_BLOCK_IMG", VK_FORMAT_PVRTC2_4BPP_SRGB_BLOCK_IMG },
        { "VK_FORMAT_R16G16_S10_5_NV", VK_FORMAT_R16G16_S10_5_NV },
        { "VK_FORMAT_A1B5G5R5_UNORM_PACK16_KHR", VK_FORMAT_A1B5G5R5_UNORM_PACK16_KHR },
        { "VK_FORMAT_A8_UNORM_KHR", VK_FORMAT_A8_UNORM_KHR },
        { "VK_FORMAT_ASTC_4x4_SFLOAT_BLOCK_EXT", VK_FORMAT_ASTC_4x4_SFLOAT_BLOCK_EXT },
        { "VK_FORMAT_ASTC_5x4_SFLOAT_BLOCK_EXT", VK_FORMAT_ASTC_5x4_SFLOAT_BLOCK_EXT },
        { "VK_FORMAT_ASTC_5x5_SFLOAT_BLOCK_EXT", VK_FORMAT_ASTC_5x5_SFLOAT_BLOCK_EXT },
        { "VK_FORMAT_ASTC_6x5_SFLOAT_BLOCK_EXT", VK_FORMAT_ASTC_6x5_SFLOAT_BLOCK_EXT },
        { "VK_FORMAT_ASTC_6x6_SFLOAT_BLOCK_EXT", VK_FORMAT_ASTC_6x6_SFLOAT_BLOCK_EXT },
        { "VK_FORMAT_ASTC_8x5_SFLOAT_BLOCK_EXT", VK_FORMAT_ASTC_8x5_SFLOAT_BLOCK_EXT },
        { "VK_FORMAT_ASTC_8x6_SFLOAT_BLOCK_EXT", VK_FORMAT_ASTC_8x6_SFLOAT_BLOCK_EXT },
        { "VK_FORMAT_ASTC_8x8_SFLOAT_BLOCK_EXT", VK_FORMAT_ASTC_8x8_SFLOAT_BLOCK_EXT },
        { "VK_FORMAT_ASTC_10x5_SFLOAT_BLOCK_EXT", VK_FORMAT_ASTC_10x5_SFLOAT_BLOCK_EXT },
        { "VK_FORMAT_ASTC_10x6_SFLOAT_BLOCK_EXT", VK_FORMAT_ASTC_10x6_SFLOAT_BLOCK_EXT },
        { "VK_FORMAT_ASTC_10x8_SFLOAT_BLOCK_EXT", VK_FORMAT_ASTC_10x8_SFLOAT_BLOCK_EXT },
        { "VK_FORMAT_ASTC_10x10_SFLOAT_BLOCK_EXT", VK_FORMAT_ASTC_10x10_SFLOAT_BLOCK_EXT },
        { "VK_FORMAT_ASTC_12x10_SFLOAT_BLOCK_EXT", VK_FORMAT_ASTC_12x10_SFLOAT_BLOCK_EXT },
        { "VK_FORMAT_ASTC_12x12_SFLOAT_BLOCK_EXT", VK_FORMAT_ASTC_12x12_SFLOAT_BLOCK_EXT },
        { "VK_FORMAT_G8B8G8R8_422_UNORM_KHR", VK_FORMAT_G8B8G8R8_422_UNORM_KHR },
        { "VK_FORMAT_B8G8R8G8_422_UNORM_KHR", VK_FORMAT_B8G8R8G8_422_UNORM_KHR },
        { "VK_FORMAT_G8_B8_R8_3PLANE_420_UNORM_KHR", VK_FORMAT_G8_B8_R8_3PLANE_420_UNORM_KHR },
        { "VK_FORMAT_G8_B8R8_2PLANE_420_UNORM_KHR", VK_FORMAT_G8_B8R8_2PLANE_420_UNORM_KHR },
        { "VK_FORMAT_G8_B8_R8_3PLANE_422_UNORM_KHR", VK_FORMAT_G8_B8_R8_3PLANE_422_UNORM_KHR },
        { "VK_FORMAT_G8_B8R8_2PLANE_422_UNORM_KHR", VK_FORMAT_G8_B8R8_2PLANE_422_UNORM_KHR },
        { "VK_FORMAT_G8_B8_R8_3PLANE_444_UNORM_KHR", VK_FORMAT_G8_B8_R8_3PLANE_444_UNORM_KHR },
        { "VK_FORMAT_R10X6_UNORM_PACK16_KHR", VK_FORMAT_R10X6_UNORM_PACK16_KHR },
        { "VK_FORMAT_R10X6G10X6_UNORM_2PACK16_KHR", VK_FORMAT_R10X6G10X6_UNORM_2PACK16_KHR },
        { "VK_FORMAT_R10X6G10X6B10X6A10X6_UNORM_4PACK16_KHR", VK_FORMAT_R10X6G10X6B10X6A10X6_UNORM_4PACK16_KHR },
        { "VK_FORMAT_G10X6B10X6G10X6R10X6_422_UNORM_4PACK16_KHR", VK_FORMAT_G10X6B10X6G10X6R10X6_422_UNORM_4PACK16_KHR },
        { "VK_FORMAT_B10X6G10X6R10X6G10X6_422_UNORM_4PACK16_KHR", VK_FORMAT_B10X6G10X6R10X6G10X6_422_UNORM_4PACK16_KHR },
        { "VK_FORMAT_G10X6_B10X6_R10X6_3PLANE_420_UNORM_3PACK16_KHR", VK_FORMAT_G10X6_B10X6_R10X6_3PLANE_420_UNORM_3PACK16_KHR },
        { "VK_FORMAT_G10X6_B10X6R10X6_2PLANE_420_UNORM_3PACK16_KHR", VK_FORMAT_G10X6_B10X6R10X6_2PLANE_420_UNORM_3PACK16_KHR },
        { "VK_FORMAT_G10X6_B10X6_R10X6_3PLANE_422_UNORM_3PACK16_KHR", VK_FORMAT_G10X6_B10X6_R10X6_3PLANE_422_UNORM_3PACK16_KHR },
        { "VK_FORMAT_G10X6_B10X6R10X6_2PLANE_422_UNORM_3PACK16_KHR", VK_FORMAT_G10X6_B10X6R10X6_2PLANE_422_UNORM_3PACK16_KHR },
        { "VK_FORMAT_G10X6_B10X6_R10X6_3PLANE_444_UNORM_3PACK16_KHR", VK_FORMAT_G10X6_B10X6_R10X6_3PLANE_444_UNORM_3PACK16_KHR },
        { "VK_FORMAT_R12X4_UNORM_PACK16_KHR", VK_FORMAT_R12X4_UNORM_PACK16_KHR },
        { "VK_FORMAT_R12X4G12X4_UNORM_2PACK16_KHR", VK_FORMAT_R12X4G12X4_UNORM_2PACK16_KHR },
        { "VK_FORMAT_R12X4G12X4B12X4A12X4_UNORM_4PACK16_KHR", VK_FORMAT_R12X4G12X4B12X4A12X4_UNORM_4PACK16_KHR },
        { "VK_FORMAT_G12X4B12X4G12X4R12X4_422_UNORM_4PACK16_KHR", VK_FORMAT_G12X4B12X4G12X4R12X4_422_UNORM_4PACK16_KHR },
        { "VK_FORMAT_B12X4G12X4R12X4G12X4_422_UNORM_4PACK16_KHR", VK_FORMAT_B12X4G12X4R12X4G12X4_422_UNORM_4PACK16_KHR },
        { "VK_FORMAT_G12X4_B12X4_R12X4_3PLANE_420_UNORM_3PACK16_KHR", VK_FORMAT_G12X4_B12X4_R12X4_3PLANE_420_UNORM_3PACK16_KHR },
        { "VK_FORMAT_G12X4_B12X4R12X4_2PLANE_420_UNORM_3PACK16_KHR", VK_FORMAT_G12X4_B12X4R12X4_2PLANE_420_UNORM_3PACK16_KHR },
        { "VK_FORMAT_G12X4_B12X4_R12X4_3PLANE_422_UNORM_3PACK16_KHR", VK_FORMAT_G12X4_B12X4_R12X4_3PLANE_422_UNORM_3PACK16_KHR },
        { "VK_FORMAT_G12X4_B12X4R12X4_2PLANE_422_UNORM_3PACK16_KHR", VK_FORMAT_G12X4_B12X4R12X4_2PLANE_422_UNORM_3PACK16_KHR },
        { "VK_FORMAT_G12X4_B12X4_R12X4_3PLANE_444_UNORM_3PACK16_KHR", VK_FORMAT_G12X4_B12X4_R12X4_3PLANE_444_UNORM_3PACK16_KHR },
        { "VK_FORMAT_G16B16G16R16_422_UNORM_KHR", VK_FORMAT_G16B16G16R16_422_UNORM_KHR },
        { "VK_FORMAT_B16G16R16G16_422_UNORM_KHR", VK_FORMAT_B16G16R16G16_422_UNORM_KHR },
        { "VK_FORMAT_G16_B16_R16_3PLANE_420_UNORM_KHR", VK_FORMAT_G16_B16_R16_3PLANE_420_UNORM_KHR },
        { "VK_FORMAT_G16_B16R16_2PLANE_420_UNORM_KHR", VK_FORMAT_G16_B16R16_2PLANE_420_UNORM_KHR },
        { "VK_FORMAT_G16_B16_R16_3PLANE_422_UNORM_KHR", VK_FORMAT_G16_B16_R16_3PLANE_422_UNORM_KHR },
        { "VK_FORMAT_G16_B16R16_2PLANE_422_UNORM_KHR", VK_FORMAT_G16_B16R16_2PLANE_422_UNORM_KHR },
        { "VK_FORMAT_G16_B16_R16_3PLANE_444_UNORM_KHR", VK_FORMAT_G16_B16_R16_3PLANE_444_UNORM_KHR },
        { "VK_FORMAT_G8_B8R8_2PLANE_444_UNORM_EXT", VK_FORMAT_G8_B8R8_2PLANE_444_UNORM_EXT },
        { "VK_FORMAT_G10X6_B10X6R10X6_2PLANE_444_UNORM_3PACK16_EXT", VK_FORMAT_G10X6_B10X6R10X6_2PLANE_444_UNORM_3PACK16_EXT },
        { "VK_FORMAT_G12X4_B12X4R12X4_2PLANE_444_UNORM_3PACK16_EXT", VK_FORMAT_G12X4_B12X4R12X4_2PLANE_444_UNORM_3PACK16_EXT },
        { "VK_FORMAT_G16_B16R16_2PLANE_444_UNORM_EXT", VK_FORMAT_G16_B16R16_2PLANE_444_UNORM_EXT },
        { "VK_FORMAT_A4R4G4B4_UNORM_PACK16_EXT", VK_FORMAT_A4R4G4B4_UNORM_PACK16_EXT },
        { "VK_FORMAT_A4B4G4R4_UNORM_PACK16_EXT", VK_FORMAT_A4B4G4R4_UNORM_PACK16_EXT }
    };

    auto it = convertMap.find(format);

    if (it != convertMap.end())
        return it->second;
    else
        return def;
}

VkPrimitiveTopology VulkanConversions::VkPrimitiveTopologyFromString(const std::string& str, VkPrimitiveTopology def)
{
    static std::unordered_map<std::string_view, VkPrimitiveTopology> convertMap = {
        { "VK_PRIMITIVE_TOPOLOGY_POINT_LIST", VK_PRIMITIVE_TOPOLOGY_POINT_LIST },
        { "VK_PRIMITIVE_TOPOLOGY_LINE_LIST", VK_PRIMITIVE_TOPOLOGY_LINE_LIST },
        { "VK_PRIMITIVE_TOPOLOGY_LINE_STRIP", VK_PRIMITIVE_TOPOLOGY_LINE_STRIP },
        { "VK_PRIMITIVE_TOPOLOGY_TRIANGLE_LIST", VK_PRIMITIVE_TOPOLOGY_TRIANGLE_LIST },
        { "VK_PRIMITIVE_TOPOLOGY_TRIANGLE_STRIP", VK_PRIMITIVE_TOPOLOGY_TRIANGLE_STRIP },
        { "VK_PRIMITIVE_TOPOLOGY_TRIANGLE_FAN", VK_PRIMITIVE_TOPOLOGY_TRIANGLE_FAN },
        { "VK_PRIMITIVE_TOPOLOGY_LINE_LIST_WITH_ADJACENCY", VK_PRIMITIVE_TOPOLOGY_LINE_LIST_WITH_ADJACENCY },
        { "VK_PRIMITIVE_TOPOLOGY_LINE_STRIP_WITH_ADJACENCY", VK_PRIMITIVE_TOPOLOGY_LINE_STRIP_WITH_ADJACENCY },
        { "VK_PRIMITIVE_TOPOLOGY_TRIANGLE_LIST_WITH_ADJACENCY", VK_PRIMITIVE_TOPOLOGY_TRIANGLE_LIST_WITH_ADJACENCY },
        { "VK_PRIMITIVE_TOPOLOGY_TRIANGLE_STRIP_WITH_ADJACENCY", VK_PRIMITIVE_TOPOLOGY_TRIANGLE_STRIP_WITH_ADJACENCY },
        { "VK_PRIMITIVE_TOPOLOGY_PATCH_LIST", VK_PRIMITIVE_TOPOLOGY_PATCH_LIST },
    };

    auto it = convertMap.find(str);

    if (it != convertMap.end())
        return it->second;
    else
        return def;
}

VkVertexInputRate VulkanConversions::VkVertexInputRateFromString(const std::string& str, VkVertexInputRate def)
{
    static std::unordered_map<std::string_view, VkVertexInputRate> convertMap = {
        { "VK_VERTEX_INPUT_RATE_VERTEX", VK_VERTEX_INPUT_RATE_VERTEX },
        { "VK_VERTEX_INPUT_RATE_INSTANCE", VK_VERTEX_INPUT_RATE_INSTANCE },
    };

    auto it = convertMap.find(str);

    if (it != convertMap.end())
        return it->second;
    else
        return def;
}

VkPolygonMode VulkanConversions::VkPolygonModeFromString(const std::string& str, VkPolygonMode def)
{
    static std::unordered_map<std::string_view, VkPolygonMode> convertMap = {
        { "VK_POLYGON_MODE_FILL", VK_POLYGON_MODE_FILL },
        { "VK_POLYGON_MODE_LINE", VK_POLYGON_MODE_LINE },
        { "VK_POLYGON_MODE_POINT", VK_POLYGON_MODE_POINT },
        { "VK_POLYGON_MODE_FILL_RECTANGLE_NV", VK_POLYGON_MODE_FILL_RECTANGLE_NV },
    };

    auto it = convertMap.find(str);

    if (it != convertMap.end())
        return it->second;
    else
        return def;
}

VkCullModeFlags VulkanConversions::VkCullModeFlagsFromString(const std::string& str, VkCullModeFlags def)
{
    static std::unordered_map<std::string_view, VkCullModeFlagBits> convertMap = {
        { "VK_CULL_MODE_NONE", VK_CULL_MODE_NONE },
        { "VK_CULL_MODE_FRONT_BIT", VK_CULL_MODE_FRONT_BIT },
        { "VK_CULL_MODE_BACK_BIT", VK_CULL_MODE_BACK_BIT },
        { "VK_CULL_MODE_FRONT_AND_BACK", VK_CULL_MODE_FRONT_AND_BACK },
    };

    std::string clean = str;
    std::erase_if(clean, isspace);

    VkCullModeFlags flags = 0;
    std::istringstream stream(clean);
    std::string item;
    bool foundFlag = false;
    while (std::getline(stream, item, '|')) {
        auto it = convertMap.find(item);
        if (it != convertMap.end()) {
            flags |= it->second;
            foundFlag = true;
        }
    }

    if (!foundFlag) {
        return flags;
    }

    return def;
}

VkFrontFace VulkanConversions::VkFrontFaceFromString(const std::string& str, VkFrontFace def)
{
    static std::unordered_map<std::string_view, VkFrontFace> convertMap = {
        { "VK_FRONT_FACE_COUNTER_CLOCKWISE", VK_FRONT_FACE_COUNTER_CLOCKWISE },
        { "VK_FRONT_FACE_CLOCKWISE", VK_FRONT_FACE_CLOCKWISE },
    };

    auto it = convertMap.find(str);

    if (it != convertMap.end())
        return it->second;
    else
        return def;

}

VkCompareOp VulkanConversions::VkCompareOpFromString(const std::string& str, VkCompareOp def)
{
    static std::unordered_map<std::string_view, VkCompareOp> convertMap = {
        { "VK_COMPARE_OP_NEVER", VK_COMPARE_OP_NEVER},
        { "VK_COMPARE_OP_LESS", VK_COMPARE_OP_LESS},
        { "VK_COMPARE_OP_EQUAL", VK_COMPARE_OP_EQUAL},
        { "VK_COMPARE_OP_LESS_OR_EQUAL", VK_COMPARE_OP_LESS_OR_EQUAL},
        { "VK_COMPARE_OP_GREATER", VK_COMPARE_OP_GREATER},
        { "VK_COMPARE_OP_NOT_EQUAL", VK_COMPARE_OP_NOT_EQUAL},
        { "VK_COMPARE_OP_GREATER_OR_EQUAL", VK_COMPARE_OP_GREATER_OR_EQUAL},
        { "VK_COMPARE_OP_ALWAYS", VK_COMPARE_OP_ALWAYS},
    };

    auto it = convertMap.find(str);
    if (it != convertMap.end()) {
        return it->second;
    }

    return def;
}

VkStencilOp VulkanConversions::VkStencilOpFromString(const std::string& str, VkStencilOp def)
{
    static std::unordered_map<std::string_view, VkStencilOp> convertMap = {
        { "VK_STENCIL_OP_KEEP", VK_STENCIL_OP_KEEP },
        { "VK_STENCIL_OP_ZERO", VK_STENCIL_OP_ZERO },
        { "VK_STENCIL_OP_REPLACE", VK_STENCIL_OP_REPLACE },
        { "VK_STENCIL_OP_INCREMENT_AND_CLAMP", VK_STENCIL_OP_INCREMENT_AND_CLAMP },
        { "VK_STENCIL_OP_DECREMENT_AND_CLAMP", VK_STENCIL_OP_DECREMENT_AND_CLAMP },
        { "VK_STENCIL_OP_INVERT", VK_STENCIL_OP_INVERT },
        { "VK_STENCIL_OP_INCREMENT_AND_WRAP", VK_STENCIL_OP_INCREMENT_AND_WRAP },
        { "VK_STENCIL_OP_DECREMENT_AND_WRAP", VK_STENCIL_OP_DECREMENT_AND_WRAP },
    };

    auto it = convertMap.find(str);
    if (it != convertMap.end()) {
        return it->second;
    }

    return def;
}

bool VulkanConversions::VkDynamicStateFromString(const std::string& str, VkDynamicState& out)
{
    static std::unordered_map<std::string_view, VkDynamicState> convertMap = {
        {"VK_DYNAMIC_STATE_VIEWPORT", VK_DYNAMIC_STATE_VIEWPORT},
        {"VK_DYNAMIC_STATE_SCISSOR", VK_DYNAMIC_STATE_SCISSOR},
        {"VK_DYNAMIC_STATE_LINE_WIDTH", VK_DYNAMIC_STATE_LINE_WIDTH},
        {"VK_DYNAMIC_STATE_DEPTH_BIAS", VK_DYNAMIC_STATE_DEPTH_BIAS},
        {"VK_DYNAMIC_STATE_BLEND_CONSTANTS", VK_DYNAMIC_STATE_BLEND_CONSTANTS},
        {"VK_DYNAMIC_STATE_DEPTH_BOUNDS", VK_DYNAMIC_STATE_DEPTH_BOUNDS},
        {"VK_DYNAMIC_STATE_STENCIL_COMPARE_MASK", VK_DYNAMIC_STATE_STENCIL_COMPARE_MASK},
        {"VK_DYNAMIC_STATE_STENCIL_WRITE_MASK", VK_DYNAMIC_STATE_STENCIL_WRITE_MASK},
        {"VK_DYNAMIC_STATE_STENCIL_REFERENCE", VK_DYNAMIC_STATE_STENCIL_REFERENCE},
        {"VK_DYNAMIC_STATE_CULL_MODE", VK_DYNAMIC_STATE_CULL_MODE},
        {"VK_DYNAMIC_STATE_FRONT_FACE", VK_DYNAMIC_STATE_FRONT_FACE},
        {"VK_DYNAMIC_STATE_PRIMITIVE_TOPOLOGY", VK_DYNAMIC_STATE_PRIMITIVE_TOPOLOGY},
        {"VK_DYNAMIC_STATE_VIEWPORT_WITH_COUNT", VK_DYNAMIC_STATE_VIEWPORT_WITH_COUNT},
        {"VK_DYNAMIC_STATE_SCISSOR_WITH_COUNT", VK_DYNAMIC_STATE_SCISSOR_WITH_COUNT},
        {"VK_DYNAMIC_STATE_VERTEX_INPUT_BINDING_STRIDE", VK_DYNAMIC_STATE_VERTEX_INPUT_BINDING_STRIDE},
        {"VK_DYNAMIC_STATE_DEPTH_TEST_ENABLE", VK_DYNAMIC_STATE_DEPTH_TEST_ENABLE},
        {"VK_DYNAMIC_STATE_DEPTH_WRITE_ENABLE", VK_DYNAMIC_STATE_DEPTH_WRITE_ENABLE},
        {"VK_DYNAMIC_STATE_DEPTH_COMPARE_OP", VK_DYNAMIC_STATE_DEPTH_COMPARE_OP},
        {"VK_DYNAMIC_STATE_DEPTH_BOUNDS_TEST_ENABLE", VK_DYNAMIC_STATE_DEPTH_BOUNDS_TEST_ENABLE},
        {"VK_DYNAMIC_STATE_STENCIL_TEST_ENABLE", VK_DYNAMIC_STATE_STENCIL_TEST_ENABLE},
        {"VK_DYNAMIC_STATE_STENCIL_OP", VK_DYNAMIC_STATE_STENCIL_OP},
        {"VK_DYNAMIC_STATE_RASTERIZER_DISCARD_ENABLE", VK_DYNAMIC_STATE_RASTERIZER_DISCARD_ENABLE},
        {"VK_DYNAMIC_STATE_DEPTH_BIAS_ENABLE", VK_DYNAMIC_STATE_DEPTH_BIAS_ENABLE},
        {"VK_DYNAMIC_STATE_PRIMITIVE_RESTART_ENABLE", VK_DYNAMIC_STATE_PRIMITIVE_RESTART_ENABLE},
        {"VK_DYNAMIC_STATE_LINE_STIPPLE", VK_DYNAMIC_STATE_LINE_STIPPLE},
        {"VK_DYNAMIC_STATE_VIEWPORT_W_SCALING_NV", VK_DYNAMIC_STATE_VIEWPORT_W_SCALING_NV},
        {"VK_DYNAMIC_STATE_DISCARD_RECTANGLE_EXT", VK_DYNAMIC_STATE_DISCARD_RECTANGLE_EXT},
        {"VK_DYNAMIC_STATE_DISCARD_RECTANGLE_ENABLE_EXT", VK_DYNAMIC_STATE_DISCARD_RECTANGLE_ENABLE_EXT},
        {"VK_DYNAMIC_STATE_DISCARD_RECTANGLE_MODE_EXT", VK_DYNAMIC_STATE_DISCARD_RECTANGLE_MODE_EXT},
        {"VK_DYNAMIC_STATE_SAMPLE_LOCATIONS_EXT", VK_DYNAMIC_STATE_SAMPLE_LOCATIONS_EXT},
        {"VK_DYNAMIC_STATE_RAY_TRACING_PIPELINE_STACK_SIZE_KHR", VK_DYNAMIC_STATE_RAY_TRACING_PIPELINE_STACK_SIZE_KHR},
        {"VK_DYNAMIC_STATE_VIEWPORT_SHADING_RATE_PALETTE_NV", VK_DYNAMIC_STATE_VIEWPORT_SHADING_RATE_PALETTE_NV},
        {"VK_DYNAMIC_STATE_VIEWPORT_COARSE_SAMPLE_ORDER_NV", VK_DYNAMIC_STATE_VIEWPORT_COARSE_SAMPLE_ORDER_NV},
        {"VK_DYNAMIC_STATE_EXCLUSIVE_SCISSOR_ENABLE_NV", VK_DYNAMIC_STATE_EXCLUSIVE_SCISSOR_ENABLE_NV},
        {"VK_DYNAMIC_STATE_EXCLUSIVE_SCISSOR_NV", VK_DYNAMIC_STATE_EXCLUSIVE_SCISSOR_NV},
        {"VK_DYNAMIC_STATE_FRAGMENT_SHADING_RATE_KHR", VK_DYNAMIC_STATE_FRAGMENT_SHADING_RATE_KHR},
        {"VK_DYNAMIC_STATE_VERTEX_INPUT_EXT", VK_DYNAMIC_STATE_VERTEX_INPUT_EXT},
        {"VK_DYNAMIC_STATE_PATCH_CONTROL_POINTS_EXT", VK_DYNAMIC_STATE_PATCH_CONTROL_POINTS_EXT},
        {"VK_DYNAMIC_STATE_LOGIC_OP_EXT", VK_DYNAMIC_STATE_LOGIC_OP_EXT},
        {"VK_DYNAMIC_STATE_COLOR_WRITE_ENABLE_EXT", VK_DYNAMIC_STATE_COLOR_WRITE_ENABLE_EXT},
        {"VK_DYNAMIC_STATE_DEPTH_CLAMP_ENABLE_EXT", VK_DYNAMIC_STATE_DEPTH_CLAMP_ENABLE_EXT},
        {"VK_DYNAMIC_STATE_POLYGON_MODE_EXT", VK_DYNAMIC_STATE_POLYGON_MODE_EXT},
        {"VK_DYNAMIC_STATE_RASTERIZATION_SAMPLES_EXT", VK_DYNAMIC_STATE_RASTERIZATION_SAMPLES_EXT},
        {"VK_DYNAMIC_STATE_SAMPLE_MASK_EXT", VK_DYNAMIC_STATE_SAMPLE_MASK_EXT},
        {"VK_DYNAMIC_STATE_ALPHA_TO_COVERAGE_ENABLE_EXT", VK_DYNAMIC_STATE_ALPHA_TO_COVERAGE_ENABLE_EXT},
        {"VK_DYNAMIC_STATE_ALPHA_TO_ONE_ENABLE_EXT", VK_DYNAMIC_STATE_ALPHA_TO_ONE_ENABLE_EXT},
        {"VK_DYNAMIC_STATE_LOGIC_OP_ENABLE_EXT", VK_DYNAMIC_STATE_LOGIC_OP_ENABLE_EXT},
        {"VK_DYNAMIC_STATE_COLOR_BLEND_ENABLE_EXT", VK_DYNAMIC_STATE_COLOR_BLEND_ENABLE_EXT},
        {"VK_DYNAMIC_STATE_COLOR_BLEND_EQUATION_EXT", VK_DYNAMIC_STATE_COLOR_BLEND_EQUATION_EXT},
        {"VK_DYNAMIC_STATE_COLOR_WRITE_MASK_EXT", VK_DYNAMIC_STATE_COLOR_WRITE_MASK_EXT},
        {"VK_DYNAMIC_STATE_TESSELLATION_DOMAIN_ORIGIN_EXT", VK_DYNAMIC_STATE_TESSELLATION_DOMAIN_ORIGIN_EXT},
        {"VK_DYNAMIC_STATE_RASTERIZATION_STREAM_EXT", VK_DYNAMIC_STATE_RASTERIZATION_STREAM_EXT},
        {"VK_DYNAMIC_STATE_CONSERVATIVE_RASTERIZATION_MODE_EXT", VK_DYNAMIC_STATE_CONSERVATIVE_RASTERIZATION_MODE_EXT},
        {"VK_DYNAMIC_STATE_EXTRA_PRIMITIVE_OVERESTIMATION_SIZE_EXT", VK_DYNAMIC_STATE_EXTRA_PRIMITIVE_OVERESTIMATION_SIZE_EXT},
        {"VK_DYNAMIC_STATE_DEPTH_CLIP_ENABLE_EXT", VK_DYNAMIC_STATE_DEPTH_CLIP_ENABLE_EXT},
        {"VK_DYNAMIC_STATE_SAMPLE_LOCATIONS_ENABLE_EXT", VK_DYNAMIC_STATE_SAMPLE_LOCATIONS_ENABLE_EXT},
        {"VK_DYNAMIC_STATE_COLOR_BLEND_ADVANCED_EXT", VK_DYNAMIC_STATE_COLOR_BLEND_ADVANCED_EXT},
        {"VK_DYNAMIC_STATE_PROVOKING_VERTEX_MODE_EXT", VK_DYNAMIC_STATE_PROVOKING_VERTEX_MODE_EXT},
        {"VK_DYNAMIC_STATE_LINE_RASTERIZATION_MODE_EXT", VK_DYNAMIC_STATE_LINE_RASTERIZATION_MODE_EXT},
        {"VK_DYNAMIC_STATE_LINE_STIPPLE_ENABLE_EXT", VK_DYNAMIC_STATE_LINE_STIPPLE_ENABLE_EXT},
        {"VK_DYNAMIC_STATE_DEPTH_CLIP_NEGATIVE_ONE_TO_ONE_EXT", VK_DYNAMIC_STATE_DEPTH_CLIP_NEGATIVE_ONE_TO_ONE_EXT},
        {"VK_DYNAMIC_STATE_VIEWPORT_W_SCALING_ENABLE_NV", VK_DYNAMIC_STATE_VIEWPORT_W_SCALING_ENABLE_NV},
        {"VK_DYNAMIC_STATE_VIEWPORT_SWIZZLE_NV", VK_DYNAMIC_STATE_VIEWPORT_SWIZZLE_NV},
        {"VK_DYNAMIC_STATE_COVERAGE_TO_COLOR_ENABLE_NV", VK_DYNAMIC_STATE_COVERAGE_TO_COLOR_ENABLE_NV},
        {"VK_DYNAMIC_STATE_COVERAGE_TO_COLOR_LOCATION_NV", VK_DYNAMIC_STATE_COVERAGE_TO_COLOR_LOCATION_NV},
        {"VK_DYNAMIC_STATE_COVERAGE_MODULATION_MODE_NV", VK_DYNAMIC_STATE_COVERAGE_MODULATION_MODE_NV},
        {"VK_DYNAMIC_STATE_COVERAGE_MODULATION_TABLE_ENABLE_NV", VK_DYNAMIC_STATE_COVERAGE_MODULATION_TABLE_ENABLE_NV},
        {"VK_DYNAMIC_STATE_COVERAGE_MODULATION_TABLE_NV", VK_DYNAMIC_STATE_COVERAGE_MODULATION_TABLE_NV},
        {"VK_DYNAMIC_STATE_SHADING_RATE_IMAGE_ENABLE_NV", VK_DYNAMIC_STATE_SHADING_RATE_IMAGE_ENABLE_NV},
        {"VK_DYNAMIC_STATE_REPRESENTATIVE_FRAGMENT_TEST_ENABLE_NV", VK_DYNAMIC_STATE_REPRESENTATIVE_FRAGMENT_TEST_ENABLE_NV},
        {"VK_DYNAMIC_STATE_COVERAGE_REDUCTION_MODE_NV", VK_DYNAMIC_STATE_COVERAGE_REDUCTION_MODE_NV},
        {"VK_DYNAMIC_STATE_ATTACHMENT_FEEDBACK_LOOP_ENABLE_EXT", VK_DYNAMIC_STATE_ATTACHMENT_FEEDBACK_LOOP_ENABLE_EXT},
        {"VK_DYNAMIC_STATE_DEPTH_CLAMP_RANGE_EXT", VK_DYNAMIC_STATE_DEPTH_CLAMP_RANGE_EXT},
        {"VK_DYNAMIC_STATE_LINE_STIPPLE_EXT", VK_DYNAMIC_STATE_LINE_STIPPLE_EXT},
        {"VK_DYNAMIC_STATE_CULL_MODE_EXT", VK_DYNAMIC_STATE_CULL_MODE_EXT},
        {"VK_DYNAMIC_STATE_FRONT_FACE_EXT", VK_DYNAMIC_STATE_FRONT_FACE_EXT},
        {"VK_DYNAMIC_STATE_PRIMITIVE_TOPOLOGY_EXT", VK_DYNAMIC_STATE_PRIMITIVE_TOPOLOGY_EXT},
        {"VK_DYNAMIC_STATE_VIEWPORT_WITH_COUNT_EXT", VK_DYNAMIC_STATE_VIEWPORT_WITH_COUNT_EXT},
        {"VK_DYNAMIC_STATE_SCISSOR_WITH_COUNT_EXT", VK_DYNAMIC_STATE_SCISSOR_WITH_COUNT_EXT},
        {"VK_DYNAMIC_STATE_VERTEX_INPUT_BINDING_STRIDE_EXT", VK_DYNAMIC_STATE_VERTEX_INPUT_BINDING_STRIDE_EXT},
        {"VK_DYNAMIC_STATE_DEPTH_TEST_ENABLE_EXT", VK_DYNAMIC_STATE_DEPTH_TEST_ENABLE_EXT},
        {"VK_DYNAMIC_STATE_DEPTH_WRITE_ENABLE_EXT", VK_DYNAMIC_STATE_DEPTH_WRITE_ENABLE_EXT},
        {"VK_DYNAMIC_STATE_DEPTH_COMPARE_OP_EXT", VK_DYNAMIC_STATE_DEPTH_COMPARE_OP_EXT},
        {"VK_DYNAMIC_STATE_DEPTH_BOUNDS_TEST_ENABLE_EXT", VK_DYNAMIC_STATE_DEPTH_BOUNDS_TEST_ENABLE_EXT},
        {"VK_DYNAMIC_STATE_STENCIL_TEST_ENABLE_EXT", VK_DYNAMIC_STATE_STENCIL_TEST_ENABLE_EXT},
        {"VK_DYNAMIC_STATE_STENCIL_OP_EXT", VK_DYNAMIC_STATE_STENCIL_OP_EXT},
        {"VK_DYNAMIC_STATE_RASTERIZER_DISCARD_ENABLE_EXT", VK_DYNAMIC_STATE_RASTERIZER_DISCARD_ENABLE_EXT},
        {"VK_DYNAMIC_STATE_DEPTH_BIAS_ENABLE_EXT", VK_DYNAMIC_STATE_DEPTH_BIAS_ENABLE_EXT},
        {"VK_DYNAMIC_STATE_PRIMITIVE_RESTART_ENABLE_EXT", VK_DYNAMIC_STATE_PRIMITIVE_RESTART_ENABLE_EXT},
        {"VK_DYNAMIC_STATE_LINE_STIPPLE_KHR", VK_DYNAMIC_STATE_LINE_STIPPLE_KHR},
    };

    auto it = convertMap.find(str);
    if (it == convertMap.end()) {
        return false;
    }

    out = it->second;
    return true;
}

std::string_view ToString(VkFormat format)
{
    switch (format) {
    case VK_FORMAT_UNDEFINED:
        return "VK_FORMAT_UNDEFINED";
    case VK_FORMAT_R4G4_UNORM_PACK8:
        return "VK_FORMAT_R4G4_UNORM_PACK8";
    case VK_FORMAT_R4G4B4A4_UNORM_PACK16:
        return "VK_FORMAT_R4G4B4A4_UNORM_PACK16";
    case VK_FORMAT_B4G4R4A4_UNORM_PACK16:
        return "VK_FORMAT_B4G4R4A4_UNORM_PACK16";
    case VK_FORMAT_R5G6B5_UNORM_PACK16:
        return "VK_FORMAT_R5G6B5_UNORM_PACK16";
    case VK_FORMAT_B5G6R5_UNORM_PACK16:
        return "VK_FORMAT_B5G6R5_UNORM_PACK16";
    case VK_FORMAT_R5G5B5A1_UNORM_PACK16:
        return "VK_FORMAT_R5G5B5A1_UNORM_PACK16";
    case VK_FORMAT_B5G5R5A1_UNORM_PACK16:
        return "VK_FORMAT_B5G5R5A1_UNORM_PACK16";
    case VK_FORMAT_A1R5G5B5_UNORM_PACK16:
        return "VK_FORMAT_A1R5G5B5_UNORM_PACK16";
    case VK_FORMAT_R8_UNORM:
        return "VK_FORMAT_R8_UNORM";
    case VK_FORMAT_R8_SNORM:
        return "VK_FORMAT_R8_SNORM";
    case VK_FORMAT_R8_USCALED:
        return "VK_FORMAT_R8_USCALED";
    case VK_FORMAT_R8_SSCALED:
        return "VK_FORMAT_R8_SSCALED";
    case VK_FORMAT_R8_UINT:
        return "VK_FORMAT_R8_UINT";
    case VK_FORMAT_R8_SINT:
        return "VK_FORMAT_R8_SINT";
    case VK_FORMAT_R8_SRGB:
        return "VK_FORMAT_R8_SRGB";
    case VK_FORMAT_R8G8_UNORM:
        return "VK_FORMAT_R8G8_UNORM";
    case VK_FORMAT_R8G8_SNORM:
        return "VK_FORMAT_R8G8_SNORM";
    case VK_FORMAT_R8G8_USCALED:
        return "VK_FORMAT_R8G8_USCALED";
    case VK_FORMAT_R8G8_SSCALED:
        return "VK_FORMAT_R8G8_SSCALED";
    case VK_FORMAT_R8G8_UINT:
        return "VK_FORMAT_R8G8_UINT";
    case VK_FORMAT_R8G8_SINT:
        return "VK_FORMAT_R8G8_SINT";
    case VK_FORMAT_R8G8_SRGB:
        return "VK_FORMAT_R8G8_SRGB";
    case VK_FORMAT_R8G8B8_UNORM:
        return "VK_FORMAT_R8G8B8_UNORM";
    case VK_FORMAT_R8G8B8_SNORM:
        return "VK_FORMAT_R8G8B8_SNORM";
    case VK_FORMAT_R8G8B8_USCALED:
        return "VK_FORMAT_R8G8B8_USCALED";
    case VK_FORMAT_R8G8B8_SSCALED:
        return "VK_FORMAT_R8G8B8_SSCALED";
    case VK_FORMAT_R8G8B8_UINT:
        return "VK_FORMAT_R8G8B8_UINT";
    case VK_FORMAT_R8G8B8_SINT:
        return "VK_FORMAT_R8G8B8_SINT";
    case VK_FORMAT_R8G8B8_SRGB:
        return "VK_FORMAT_R8G8B8_SRGB";
    case VK_FORMAT_B8G8R8_UNORM:
        return "VK_FORMAT_B8G8R8_UNORM";
    case VK_FORMAT_B8G8R8_SNORM:
        return "VK_FORMAT_B8G8R8_SNORM";
    case VK_FORMAT_B8G8R8_USCALED:
        return "VK_FORMAT_B8G8R8_USCALED";
    case VK_FORMAT_B8G8R8_SSCALED:
        return "VK_FORMAT_B8G8R8_SSCALED";
    case VK_FORMAT_B8G8R8_UINT:
        return "VK_FORMAT_B8G8R8_UINT";
    case VK_FORMAT_B8G8R8_SINT:
        return "VK_FORMAT_B8G8R8_SINT";
    case VK_FORMAT_B8G8R8_SRGB:
        return "VK_FORMAT_B8G8R8_SRGB";
    case VK_FORMAT_R8G8B8A8_UNORM:
        return "VK_FORMAT_R8G8B8A8_UNORM";
    case VK_FORMAT_R8G8B8A8_SNORM:
        return "VK_FORMAT_R8G8B8A8_SNORM";
    case VK_FORMAT_R8G8B8A8_USCALED:
        return "VK_FORMAT_R8G8B8A8_USCALED";
    case VK_FORMAT_R8G8B8A8_SSCALED:
        return "VK_FORMAT_R8G8B8A8_SSCALED";
    case VK_FORMAT_R8G8B8A8_UINT:
        return "VK_FORMAT_R8G8B8A8_UINT";
    case VK_FORMAT_R8G8B8A8_SINT:
        return "VK_FORMAT_R8G8B8A8_SINT";
    case VK_FORMAT_R8G8B8A8_SRGB:
        return "VK_FORMAT_R8G8B8A8_SRGB";
    case VK_FORMAT_B8G8R8A8_UNORM:
        return "VK_FORMAT_B8G8R8A8_UNORM";
    case VK_FORMAT_B8G8R8A8_SNORM:
        return "VK_FORMAT_B8G8R8A8_SNORM";
    case VK_FORMAT_B8G8R8A8_USCALED:
        return "VK_FORMAT_B8G8R8A8_USCALED";
    case VK_FORMAT_B8G8R8A8_SSCALED:
        return "VK_FORMAT_B8G8R8A8_SSCALED";
    case VK_FORMAT_B8G8R8A8_UINT:
        return "VK_FORMAT_B8G8R8A8_UINT";
    case VK_FORMAT_B8G8R8A8_SINT:
        return "VK_FORMAT_B8G8R8A8_SINT";
    case VK_FORMAT_B8G8R8A8_SRGB:
        return "VK_FORMAT_B8G8R8A8_SRGB";
    case VK_FORMAT_A8B8G8R8_UNORM_PACK32:
        return "VK_FORMAT_A8B8G8R8_UNORM_PACK32";
    case VK_FORMAT_A8B8G8R8_SNORM_PACK32:
        return "VK_FORMAT_A8B8G8R8_SNORM_PACK32";
    case VK_FORMAT_A8B8G8R8_USCALED_PACK32:
        return "VK_FORMAT_A8B8G8R8_USCALED_PACK32";
    case VK_FORMAT_A8B8G8R8_SSCALED_PACK32:
        return "VK_FORMAT_A8B8G8R8_SSCALED_PACK32";
    case VK_FORMAT_A8B8G8R8_UINT_PACK32:
        return "VK_FORMAT_A8B8G8R8_UINT_PACK32";
    case VK_FORMAT_A8B8G8R8_SINT_PACK32:
        return "VK_FORMAT_A8B8G8R8_SINT_PACK32";
    case VK_FORMAT_A8B8G8R8_SRGB_PACK32:
        return "VK_FORMAT_A8B8G8R8_SRGB_PACK32";
    case VK_FORMAT_A2R10G10B10_UNORM_PACK32:
        return "VK_FORMAT_A2R10G10B10_UNORM_PACK32";
    case VK_FORMAT_A2R10G10B10_SNORM_PACK32:
        return "VK_FORMAT_A2R10G10B10_SNORM_PACK32";
    case VK_FORMAT_A2R10G10B10_USCALED_PACK32:
        return "VK_FORMAT_A2R10G10B10_USCALED_PACK32";
    case VK_FORMAT_A2R10G10B10_SSCALED_PACK32:
        return "VK_FORMAT_A2R10G10B10_SSCALED_PACK32";
    case VK_FORMAT_A2R10G10B10_UINT_PACK32:
        return "VK_FORMAT_A2R10G10B10_UINT_PACK32";
    case VK_FORMAT_A2R10G10B10_SINT_PACK32:
        return "VK_FORMAT_A2R10G10B10_SINT_PACK32";
    case VK_FORMAT_A2B10G10R10_UNORM_PACK32:
        return "VK_FORMAT_A2B10G10R10_UNORM_PACK32";
    case VK_FORMAT_A2B10G10R10_SNORM_PACK32:
        return "VK_FORMAT_A2B10G10R10_SNORM_PACK32";
    case VK_FORMAT_A2B10G10R10_USCALED_PACK32:
        return "VK_FORMAT_A2B10G10R10_USCALED_PACK32";
    case VK_FORMAT_A2B10G10R10_SSCALED_PACK32:
        return "VK_FORMAT_A2B10G10R10_SSCALED_PACK32";
    case VK_FORMAT_A2B10G10R10_UINT_PACK32:
        return "VK_FORMAT_A2B10G10R10_UINT_PACK32";
    case VK_FORMAT_A2B10G10R10_SINT_PACK32:
        return "VK_FORMAT_A2B10G10R10_SINT_PACK32";
    case VK_FORMAT_R16_UNORM:
        return "VK_FORMAT_R16_UNORM";
    case VK_FORMAT_R16_SNORM:
        return "VK_FORMAT_R16_SNORM";
    case VK_FORMAT_R16_USCALED:
        return "VK_FORMAT_R16_USCALED";
    case VK_FORMAT_R16_SSCALED:
        return "VK_FORMAT_R16_SSCALED";
    case VK_FORMAT_R16_UINT:
        return "VK_FORMAT_R16_UINT";
    case VK_FORMAT_R16_SINT:
        return "VK_FORMAT_R16_SINT";
    case VK_FORMAT_R16_SFLOAT:
        return "VK_FORMAT_R16_SFLOAT";
    case VK_FORMAT_R16G16_UNORM:
        return "VK_FORMAT_R16G16_UNORM";
    case VK_FORMAT_R16G16_SNORM:
        return "VK_FORMAT_R16G16_SNORM";
    case VK_FORMAT_R16G16_USCALED:
        return "VK_FORMAT_R16G16_USCALED";
    case VK_FORMAT_R16G16_SSCALED:
        return "VK_FORMAT_R16G16_SSCALED";
    case VK_FORMAT_R16G16_UINT:
        return "VK_FORMAT_R16G16_UINT";
    case VK_FORMAT_R16G16_SINT:
        return "VK_FORMAT_R16G16_SINT";
    case VK_FORMAT_R16G16_SFLOAT:
        return "VK_FORMAT_R16G16_SFLOAT";
    case VK_FORMAT_R16G16B16_UNORM:
        return "VK_FORMAT_R16G16B16_UNORM";
    case VK_FORMAT_R16G16B16_SNORM:
        return "VK_FORMAT_R16G16B16_SNORM";
    case VK_FORMAT_R16G16B16_USCALED:
        return "VK_FORMAT_R16G16B16_USCALED";
    case VK_FORMAT_R16G16B16_SSCALED:
        return "VK_FORMAT_R16G16B16_SSCALED";
    case VK_FORMAT_R16G16B16_UINT:
        return "VK_FORMAT_R16G16B16_UINT";
    case VK_FORMAT_R16G16B16_SINT:
        return "VK_FORMAT_R16G16B16_SINT";
    case VK_FORMAT_R16G16B16_SFLOAT:
        return "VK_FORMAT_R16G16B16_SFLOAT";
    case VK_FORMAT_R16G16B16A16_UNORM:
        return "VK_FORMAT_R16G16B16A16_UNORM";
    case VK_FORMAT_R16G16B16A16_SNORM:
        return "VK_FORMAT_R16G16B16A16_SNORM";
    case VK_FORMAT_R16G16B16A16_USCALED:
        return "VK_FORMAT_R16G16B16A16_USCALED";
    case VK_FORMAT_R16G16B16A16_SSCALED:
        return "VK_FORMAT_R16G16B16A16_SSCALED";
    case VK_FORMAT_R16G16B16A16_UINT:
        return "VK_FORMAT_R16G16B16A16_UINT";
    case VK_FORMAT_R16G16B16A16_SINT:
        return "VK_FORMAT_R16G16B16A16_SINT";
    case VK_FORMAT_R16G16B16A16_SFLOAT:
        return "VK_FORMAT_R16G16B16A16_SFLOAT";
    case VK_FORMAT_R32_UINT:
        return "VK_FORMAT_R32_UINT";
    case VK_FORMAT_R32_SINT:
        return "VK_FORMAT_R32_SINT";
    case VK_FORMAT_R32_SFLOAT:
        return "VK_FORMAT_R32_SFLOAT";
    case VK_FORMAT_R32G32_UINT:
        return "VK_FORMAT_R32G32_UINT";
    case VK_FORMAT_R32G32_SINT:
        return "VK_FORMAT_R32G32_SINT";
    case VK_FORMAT_R32G32_SFLOAT:
        return "VK_FORMAT_R32G32_SFLOAT";
    case VK_FORMAT_R32G32B32_UINT:
        return "VK_FORMAT_R32G32B32_UINT";
    case VK_FORMAT_R32G32B32_SINT:
        return "VK_FORMAT_R32G32B32_SINT";
    case VK_FORMAT_R32G32B32_SFLOAT:
        return "VK_FORMAT_R32G32B32_SFLOAT";
    case VK_FORMAT_R32G32B32A32_UINT:
        return "VK_FORMAT_R32G32B32A32_UINT";
    case VK_FORMAT_R32G32B32A32_SINT:
        return "VK_FORMAT_R32G32B32A32_SINT";
    case VK_FORMAT_R32G32B32A32_SFLOAT:
        return "VK_FORMAT_R32G32B32A32_SFLOAT";
    case VK_FORMAT_R64_UINT:
        return "VK_FORMAT_R64_UINT";
    case VK_FORMAT_R64_SINT:
        return "VK_FORMAT_R64_SINT";
    case VK_FORMAT_R64_SFLOAT:
        return "VK_FORMAT_R64_SFLOAT";
    case VK_FORMAT_R64G64_UINT:
        return "VK_FORMAT_R64G64_UINT";
    case VK_FORMAT_R64G64_SINT:
        return "VK_FORMAT_R64G64_SINT";
    case VK_FORMAT_R64G64_SFLOAT:
        return "VK_FORMAT_R64G64_SFLOAT";
    case VK_FORMAT_R64G64B64_UINT:
        return "VK_FORMAT_R64G64B64_UINT";
    case VK_FORMAT_R64G64B64_SINT:
        return "VK_FORMAT_R64G64B64_SINT";
    case VK_FORMAT_R64G64B64_SFLOAT:
        return "VK_FORMAT_R64G64B64_SFLOAT";
    case VK_FORMAT_R64G64B64A64_UINT:
        return "VK_FORMAT_R64G64B64A64_UINT";
    case VK_FORMAT_R64G64B64A64_SINT:
        return "VK_FORMAT_R64G64B64A64_SINT";
    case VK_FORMAT_R64G64B64A64_SFLOAT:
        return "VK_FORMAT_R64G64B64A64_SFLOAT";
    case VK_FORMAT_B10G11R11_UFLOAT_PACK32:
        return "VK_FORMAT_B10G11R11_UFLOAT_PACK32";
    case VK_FORMAT_E5B9G9R9_UFLOAT_PACK32:
        return "VK_FORMAT_E5B9G9R9_UFLOAT_PACK322";
    default:
        return "UNDEFINED";
    }
}

std::string_view ToString(VkPresentModeKHR presentMode)
{
    switch (presentMode) {
    case VK_PRESENT_MODE_IMMEDIATE_KHR:
        return "VK_PRESENT_MODE_IMMEDIATE_KHR";
    case VK_PRESENT_MODE_MAILBOX_KHR:
        return "VK_PRESENT_MODE_MAILBOX_KHR";
    case VK_PRESENT_MODE_FIFO_KHR:
        return "VK_PRESENT_MODE_FIFO_KHR";
    case VK_PRESENT_MODE_FIFO_RELAXED_KHR:
        return "VK_PRESENT_MODE_FIFO_RELAXED_KHR";
#ifdef VK_VERSION_1_4
    case VK_PRESENT_MODE_FIFO_LATEST_READY_EXT:
        return "VK_PRESENT_MODE_FIFO_LATEST_READY_EXT";
#endif
    case VK_PRESENT_MODE_SHARED_DEMAND_REFRESH_KHR:
        return "VK_PRESENT_MODE_SHARED_DEMAND_REFRESH_KHR";
    case VK_PRESENT_MODE_SHARED_CONTINUOUS_REFRESH_KHR:
        return "VK_PRESENT_MODE_SHARED_CONTINUOUS_REFRESH_KHR";
    default:
        return "VK_PRESENT_MODE_UNKNOWN";
    }
}

std::string_view ToString(VkVertexInputRate rate)
{
    switch (rate) {
    case VK_VERTEX_INPUT_RATE_VERTEX:
        return "VK_VERTEX_INPUT_RATE_VERTEX";
    case VK_VERTEX_INPUT_RATE_INSTANCE:
        return "VK_VERTEX_INPUT_RATE_INSTANCE";
    default:
        return "VK_VERTEX_INPUT_RATE_(ERROR)";
    }
}

std::string_view ToString(VkPrimitiveTopology topology)
{
    switch (topology) {
    case VK_PRIMITIVE_TOPOLOGY_POINT_LIST:
        return "VK_PRIMITIVE_TOPOLOGY_POINT_LIST";
    case VK_PRIMITIVE_TOPOLOGY_LINE_LIST:
        return "VK_PRIMITIVE_TOPOLOGY_LINE_LIST";
    case VK_PRIMITIVE_TOPOLOGY_LINE_STRIP:
        return "VK_PRIMITIVE_TOPOLOGY_LINE_STRIP";
    case VK_PRIMITIVE_TOPOLOGY_TRIANGLE_LIST:
        return "VK_PRIMITIVE_TOPOLOGY_TRIANGLE_LIST";
    case VK_PRIMITIVE_TOPOLOGY_TRIANGLE_STRIP:
        return "VK_PRIMITIVE_TOPOLOGY_TRIANGLE_STRIP";
    case VK_PRIMITIVE_TOPOLOGY_TRIANGLE_FAN:
        return "VK_PRIMITIVE_TOPOLOGY_TRIANGLE_FAN";
    case VK_PRIMITIVE_TOPOLOGY_LINE_LIST_WITH_ADJACENCY:
        return "VK_PRIMITIVE_TOPOLOGY_LINE_LIST_WITH_ADJACENCY";
    case VK_PRIMITIVE_TOPOLOGY_LINE_STRIP_WITH_ADJACENCY:
        return "VK_PRIMITIVE_TOPOLOGY_LINE_STRIP_WITH_ADJACENCY";
    case VK_PRIMITIVE_TOPOLOGY_TRIANGLE_LIST_WITH_ADJACENCY:
        return "VK_PRIMITIVE_TOPOLOGY_TRIANGLE_LIST_WITH_ADJACENCY";
    case VK_PRIMITIVE_TOPOLOGY_TRIANGLE_STRIP_WITH_ADJACENCY:
        return "VK_PRIMITIVE_TOPOLOGY_TRIANGLE_STRIP_WITH_ADJACENCY";
    case VK_PRIMITIVE_TOPOLOGY_PATCH_LIST:
        return "VK_PRIMITIVE_TOPOLOGY_PATCH_LIST";
    default:
        return "VK_PRIMITIVE_TOPOLOGY_(ERROR)";
    }
}

std::string_view ToString(VkColorSpaceKHR colorSpace)
{
    switch (colorSpace) {
    case VK_COLOR_SPACE_SRGB_NONLINEAR_KHR:
        return "VK_COLOR_SPACE_SRGB_NONLINEAR_KHR";
    case VK_COLOR_SPACE_DISPLAY_P3_NONLINEAR_EXT:
        return "VK_COLOR_SPACE_DISPLAY_P3_NONLINEAR_EXT";
    case VK_COLOR_SPACE_EXTENDED_SRGB_LINEAR_EXT:
        return "VK_COLOR_SPACE_EXTENDED_SRGB_LINEAR_EXT";
    case VK_COLOR_SPACE_DISPLAY_P3_LINEAR_EXT:
        return "VK_COLOR_SPACE_DISPLAY_P3_LINEAR_EXT";
    case VK_COLOR_SPACE_DCI_P3_NONLINEAR_EXT:
        return "VK_COLOR_SPACE_DCI_P3_NONLINEAR_EXT";
    case VK_COLOR_SPACE_BT709_LINEAR_EXT:
        return "VK_COLOR_SPACE_BT709_LINEAR_EXT";
    case VK_COLOR_SPACE_BT709_NONLINEAR_EXT:
        return "VK_COLOR_SPACE_BT709_NONLINEAR_EXT";
    case VK_COLOR_SPACE_BT2020_LINEAR_EXT:
        return "VK_COLOR_SPACE_BT2020_LINEAR_EXT";
    case VK_COLOR_SPACE_HDR10_ST2084_EXT:
        return "VK_COLOR_SPACE_HDR10_ST2084_EXT";
    case VK_COLOR_SPACE_DOLBYVISION_EXT:
        return "VK_COLOR_SPACE_DOLBYVISION_EXT";
    case VK_COLOR_SPACE_HDR10_HLG_EXT:
        return "VK_COLOR_SPACE_HDR10_HLG_EXT";
    case VK_COLOR_SPACE_ADOBERGB_LINEAR_EXT:
        return "VK_COLOR_SPACE_ADOBERGB_LINEAR_EXT";
    case VK_COLOR_SPACE_ADOBERGB_NONLINEAR_EXT:
        return "VK_COLOR_SPACE_ADOBERGB_NONLINEAR_EXT";
    case VK_COLOR_SPACE_PASS_THROUGH_EXT:
        return "VK_COLOR_SPACE_PASS_THROUGH_EXT";
    case VK_COLOR_SPACE_EXTENDED_SRGB_NONLINEAR_EXT:
        return "VK_COLOR_SPACE_EXTENDED_SRGB_NONLINEAR_EXT";
    case VK_COLOR_SPACE_DISPLAY_NATIVE_AMD:
        return "VK_COLOR_SPACE_DISPLAY_NATIVE_AMD";
    default:
        return "VK_COLOR_SPACE_(ERROR)";
    }
}

std::string_view ToString(VkSampleCountFlagBits flag)
{
    switch (flag) {
    case VK_SAMPLE_COUNT_1_BIT:
        return "VK_SAMPLE_COUNT_1_BIT";
    case VK_SAMPLE_COUNT_2_BIT:
        return "VK_SAMPLE_COUNT_2_BIT";
    case VK_SAMPLE_COUNT_4_BIT:
        return "VK_SAMPLE_COUNT_4_BIT";
    case VK_SAMPLE_COUNT_8_BIT:
        return "VK_SAMPLE_COUNT_8_BIT";
    case VK_SAMPLE_COUNT_16_BIT:
        return "VK_SAMPLE_COUNT_16_BIT";
    case VK_SAMPLE_COUNT_32_BIT:
        return "VK_SAMPLE_COUNT_32_BIT";
    case VK_SAMPLE_COUNT_64_BIT:
        return "VK_SAMPLE_COUNT_64_BIT";
    default:
        return "VK_SAMPLE_COUNT_UNKNOWN";
    }
}

} // namespace bl