#pragma once

#include <nlohmann/json.hpp>

#include "Math/Extent.h"
#include "Vulkan.h"

#define NLOHMANN_JSON_SERIALIZE_ENUM_FLAGS(ENUM_TYPE, FLAG_TYPE, ...)                         \
    template <typename BasicJsonType>                                                         \
    inline void to_json(BasicJsonType& j, const FLAG_TYPE& flags)                             \
    {                                                                                         \
        static_assert(std::is_enum<ENUM_TYPE>::value, #ENUM_TYPE " must be an enum!");        \
        static_assert(std::is_integral<FLAG_TYPE>::value, #FLAG_TYPE " must be an integer!"); \
                                                                                              \
        static const std::pair<FLAG_TYPE, BasicJsonType> m[] = __VA_ARGS__;                   \
        for (const auto& [flag, value] : m) {                                                 \
            if (flags & flag)                                                                 \
                j.push_back(value);                                                           \
        }                                                                                     \
    }                                                                                         \
    template <typename BasicJsonType>                                                         \
    inline void from_json(const BasicJsonType& j, FLAG_TYPE& flags)                           \
    {                                                                                         \
        static_assert(std::is_enum<ENUM_TYPE>::value, #ENUM_TYPE " must be an enum!");        \
        static_assert(std::is_integral<FLAG_TYPE>::value, #FLAG_TYPE " must be an integer!"); \
                                                                                              \
        static const std::pair<FLAG_TYPE, BasicJsonType> m[] = __VA_ARGS__;                   \
        for (const auto& [flag, value] : m)                                                   \
            for (auto& name : j.size())                                                       \
                if (name == value)                                                            \
                    flags |= flag;                                                            \
    }

namespace bl {

class VulkanConversions {
public:
    static uint32_t GetFormatSize(VkFormat format);
    static VkFormat VkFormatFromString(const std::string& str, VkFormat def = VK_FORMAT_UNDEFINED);
    static VkVertexInputRate VkVertexInputRateFromString(const std::string& str, VkVertexInputRate def = VK_VERTEX_INPUT_RATE_VERTEX);
    static VkPrimitiveTopology VkPrimitiveTopologyFromString(const std::string& str, VkPrimitiveTopology def = VK_PRIMITIVE_TOPOLOGY_TRIANGLE_LIST);
    static VkPolygonMode VkPolygonModeFromString(const std::string& str, VkPolygonMode def = VK_POLYGON_MODE_FILL);
};

std::string_view ToString(VkFormat format);
std::string_view ToString(VkPresentModeKHR presentMode);
std::string_view ToString(VkVertexInputRate rate);
std::string_view ToString(VkPrimitiveTopology topology);
std::string_view ToString(VkColorSpaceKHR colorSpace);

}
NLOHMANN_DEFINE_TYPE_NON_INTRUSIVE(VkVertexInputBindingDescription, binding, stride, inputRate)
NLOHMANN_DEFINE_TYPE_NON_INTRUSIVE(VkVertexInputAttributeDescription, location, binding, format, offset)
NLOHMANN_DEFINE_TYPE_NON_INTRUSIVE_WITH_DEFAULT(VkStencilOpState, failOp, passOp, depthFailOp, compareOp, compareMask, writeMask, reference)
NLOHMANN_DEFINE_TYPE_NON_INTRUSIVE(VkPipelineColorBlendAttachmentState, blendEnable, srcColorBlendFactor, dstColorBlendFactor, colorBlendOp, srcAlphaBlendFactor, dstAlphaBlendFactor, alphaBlendOp, colorWriteMask)

NLOHMANN_JSON_SERIALIZE_ENUM(VkFormat, {
                                           { VK_FORMAT_UNDEFINED, nullptr },
                                           { VK_FORMAT_R4G4_UNORM_PACK8, "VK_FORMAT_R4G4_UNORM_PACK8" },
                                           { VK_FORMAT_R4G4B4A4_UNORM_PACK16, "VK_FORMAT_R4G4B4A4_UNORM_PACK16" },
                                           { VK_FORMAT_B4G4R4A4_UNORM_PACK16, "VK_FORMAT_B4G4R4A4_UNORM_PACK16" },
                                           { VK_FORMAT_R5G6B5_UNORM_PACK16, "VK_FORMAT_R5G6B5_UNORM_PACK16" },
                                           { VK_FORMAT_B5G6R5_UNORM_PACK16, "VK_FORMAT_B5G6R5_UNORM_PACK16" },
                                           { VK_FORMAT_R5G5B5A1_UNORM_PACK16, "VK_FORMAT_R5G5B5A1_UNORM_PACK16" },
                                           { VK_FORMAT_B5G5R5A1_UNORM_PACK16, "VK_FORMAT_B5G5R5A1_UNORM_PACK16" },
                                           { VK_FORMAT_A1R5G5B5_UNORM_PACK16, "VK_FORMAT_A1R5G5B5_UNORM_PACK16" },
                                           { VK_FORMAT_R8_UNORM, "VK_FORMAT_R8_UNORM" },
                                           { VK_FORMAT_R8_SNORM, "VK_FORMAT_R8_SNORM" },
                                           { VK_FORMAT_R8_USCALED, "VK_FORMAT_R8_USCALED" },
                                           { VK_FORMAT_R8_SSCALED, "VK_FORMAT_R8_SSCALED" },
                                           { VK_FORMAT_R8_UINT, "VK_FORMAT_R8_UINT" },
                                           { VK_FORMAT_R8_SINT, "VK_FORMAT_R8_SINT" },
                                           { VK_FORMAT_R8_SRGB, "VK_FORMAT_R8_SRGB" },
                                           { VK_FORMAT_R8G8_UNORM, "VK_FORMAT_R8G8_UNORM" },
                                           { VK_FORMAT_R8G8_SNORM, "VK_FORMAT_R8G8_SNORM" },
                                           { VK_FORMAT_R8G8_USCALED, "VK_FORMAT_R8G8_USCALED" },
                                           { VK_FORMAT_R8G8_SSCALED, "VK_FORMAT_R8G8_SSCALED" },
                                           { VK_FORMAT_R8G8_UINT, "VK_FORMAT_R8G8_UINT" },
                                           { VK_FORMAT_R8G8_SINT, "VK_FORMAT_R8G8_SINT" },
                                           { VK_FORMAT_R8G8_SRGB, "VK_FORMAT_R8G8_SRGB" },
                                           { VK_FORMAT_R8G8B8_UNORM, "VK_FORMAT_R8G8B8_UNORM" },
                                           { VK_FORMAT_R8G8B8_SNORM, "VK_FORMAT_R8G8B8_SNORM" },
                                           { VK_FORMAT_R8G8B8_USCALED, "VK_FORMAT_R8G8B8_USCALED" },
                                           { VK_FORMAT_R8G8B8_SSCALED, "VK_FORMAT_R8G8B8_SSCALED" },
                                           { VK_FORMAT_R8G8B8_UINT, "VK_FORMAT_R8G8B8_UINT" },
                                           { VK_FORMAT_R8G8B8_SINT, "VK_FORMAT_R8G8B8_SINT" },
                                           { VK_FORMAT_R8G8B8_SRGB, "VK_FORMAT_R8G8B8_SRGB" },
                                           { VK_FORMAT_B8G8R8_UNORM, "VK_FORMAT_B8G8R8_UNORM" },
                                           { VK_FORMAT_B8G8R8_SNORM, "VK_FORMAT_B8G8R8_SNORM" },
                                           { VK_FORMAT_B8G8R8_USCALED, "VK_FORMAT_B8G8R8_USCALED" },
                                           { VK_FORMAT_B8G8R8_SSCALED, "VK_FORMAT_B8G8R8_SSCALED" },
                                           { VK_FORMAT_B8G8R8_UINT, "VK_FORMAT_B8G8R8_UINT" },
                                           { VK_FORMAT_B8G8R8_SINT, "VK_FORMAT_B8G8R8_SINT" },
                                           { VK_FORMAT_B8G8R8_SRGB, "VK_FORMAT_B8G8R8_SRGB" },
                                           { VK_FORMAT_R8G8B8A8_UNORM, "VK_FORMAT_R8G8B8A8_UNORM" },
                                           { VK_FORMAT_R8G8B8A8_SNORM, "VK_FORMAT_R8G8B8A8_SNORM" },
                                           { VK_FORMAT_R8G8B8A8_USCALED, "VK_FORMAT_R8G8B8A8_USCALED" },
                                           { VK_FORMAT_R8G8B8A8_SSCALED, "VK_FORMAT_R8G8B8A8_SSCALED" },
                                           { VK_FORMAT_R8G8B8A8_UINT, "VK_FORMAT_R8G8B8A8_UINT" },
                                           { VK_FORMAT_R8G8B8A8_SINT, "VK_FORMAT_R8G8B8A8_SINT" },
                                           { VK_FORMAT_R8G8B8A8_SRGB, "VK_FORMAT_R8G8B8A8_SRGB" },
                                           { VK_FORMAT_B8G8R8A8_UNORM, "VK_FORMAT_B8G8R8A8_UNORM" },
                                           { VK_FORMAT_B8G8R8A8_SNORM, "VK_FORMAT_B8G8R8A8_SNORM" },
                                           { VK_FORMAT_B8G8R8A8_USCALED, "VK_FORMAT_B8G8R8A8_USCALED" },
                                           { VK_FORMAT_B8G8R8A8_SSCALED, "VK_FORMAT_B8G8R8A8_SSCALED" },
                                           { VK_FORMAT_B8G8R8A8_UINT, "VK_FORMAT_B8G8R8A8_UINT" },
                                           { VK_FORMAT_B8G8R8A8_SINT, "VK_FORMAT_B8G8R8A8_SINT" },
                                           { VK_FORMAT_B8G8R8A8_SRGB, "VK_FORMAT_B8G8R8A8_SRGB" },
                                           { VK_FORMAT_A8B8G8R8_UNORM_PACK32, "VK_FORMAT_A8B8G8R8_UNORM_PACK32" },
                                           { VK_FORMAT_A8B8G8R8_SNORM_PACK32, "VK_FORMAT_A8B8G8R8_SNORM_PACK32" },
                                           { VK_FORMAT_A8B8G8R8_USCALED_PACK32, "VK_FORMAT_A8B8G8R8_USCALED_PACK32" },
                                           { VK_FORMAT_A8B8G8R8_SSCALED_PACK32, "VK_FORMAT_A8B8G8R8_SSCALED_PACK32" },
                                           { VK_FORMAT_A8B8G8R8_UINT_PACK32, "VK_FORMAT_A8B8G8R8_UINT_PACK32" },
                                           { VK_FORMAT_A8B8G8R8_SINT_PACK32, "VK_FORMAT_A8B8G8R8_SINT_PACK32" },
                                           { VK_FORMAT_A8B8G8R8_SRGB_PACK32, "VK_FORMAT_A8B8G8R8_SRGB_PACK32" },
                                           { VK_FORMAT_A2R10G10B10_UNORM_PACK32, "VK_FORMAT_A2R10G10B10_UNORM_PACK32" },
                                           { VK_FORMAT_A2R10G10B10_SNORM_PACK32, "VK_FORMAT_A2R10G10B10_SNORM_PACK32" },
                                           { VK_FORMAT_A2R10G10B10_USCALED_PACK32, "VK_FORMAT_A2R10G10B10_USCALED_PACK32" },
                                           { VK_FORMAT_A2R10G10B10_SSCALED_PACK32, "VK_FORMAT_A2R10G10B10_SSCALED_PACK32" },
                                           { VK_FORMAT_A2R10G10B10_UINT_PACK32, "VK_FORMAT_A2R10G10B10_UINT_PACK32" },
                                           { VK_FORMAT_A2R10G10B10_SINT_PACK32, "VK_FORMAT_A2R10G10B10_SINT_PACK32" },
                                           { VK_FORMAT_A2B10G10R10_UNORM_PACK32, "VK_FORMAT_A2B10G10R10_UNORM_PACK32" },
                                           { VK_FORMAT_A2B10G10R10_SNORM_PACK32, "VK_FORMAT_A2B10G10R10_SNORM_PACK32" },
                                           { VK_FORMAT_A2B10G10R10_USCALED_PACK32, "VK_FORMAT_A2B10G10R10_USCALED_PACK32" },
                                           { VK_FORMAT_A2B10G10R10_SSCALED_PACK32, "VK_FORMAT_A2B10G10R10_SSCALED_PACK32" },
                                           { VK_FORMAT_A2B10G10R10_UINT_PACK32, "VK_FORMAT_A2B10G10R10_UINT_PACK32" },
                                           { VK_FORMAT_A2B10G10R10_SINT_PACK32, "VK_FORMAT_A2B10G10R10_SINT_PACK32" },
                                           { VK_FORMAT_R16_UNORM, "VK_FORMAT_R16_UNORM" },
                                           { VK_FORMAT_R16_SNORM, "VK_FORMAT_R16_SNORM" },
                                           { VK_FORMAT_R16_USCALED, "VK_FORMAT_R16_USCALED" },
                                           { VK_FORMAT_R16_SSCALED, "VK_FORMAT_R16_SSCALED" },
                                           { VK_FORMAT_R16_UINT, "VK_FORMAT_R16_UINT" },
                                           { VK_FORMAT_R16_SINT, "VK_FORMAT_R16_SINT" },
                                           { VK_FORMAT_R16_SFLOAT, "VK_FORMAT_R16_SFLOAT" },
                                           { VK_FORMAT_R16G16_UNORM, "VK_FORMAT_R16G16_UNORM" },
                                           { VK_FORMAT_R16G16_SNORM, "VK_FORMAT_R16G16_SNORM" },
                                           { VK_FORMAT_R16G16_USCALED, "VK_FORMAT_R16G16_USCALED" },
                                           { VK_FORMAT_R16G16_SSCALED, "VK_FORMAT_R16G16_SSCALED" },
                                           { VK_FORMAT_R16G16_UINT, "VK_FORMAT_R16G16_UINT" },
                                           { VK_FORMAT_R16G16_SINT, "VK_FORMAT_R16G16_SINT" },
                                           { VK_FORMAT_R16G16_SFLOAT, "VK_FORMAT_R16G16_SFLOAT" },
                                           { VK_FORMAT_R16G16B16_UNORM, "VK_FORMAT_R16G16B16_UNORM" },
                                           { VK_FORMAT_R16G16B16_SNORM, "VK_FORMAT_R16G16B16_SNORM" },
                                           { VK_FORMAT_R16G16B16_USCALED, "VK_FORMAT_R16G16B16_USCALED" },
                                           { VK_FORMAT_R16G16B16_SSCALED, "VK_FORMAT_R16G16B16_SSCALED" },
                                           { VK_FORMAT_R16G16B16_UINT, "VK_FORMAT_R16G16B16_UINT" },
                                           { VK_FORMAT_R16G16B16_SINT, "VK_FORMAT_R16G16B16_SINT" },
                                           { VK_FORMAT_R16G16B16_SFLOAT, "VK_FORMAT_R16G16B16_SFLOAT" },
                                           { VK_FORMAT_R16G16B16A16_UNORM, "VK_FORMAT_R16G16B16A16_UNORM" },
                                           { VK_FORMAT_R16G16B16A16_SNORM, "VK_FORMAT_R16G16B16A16_SNORM" },
                                           { VK_FORMAT_R16G16B16A16_USCALED, "VK_FORMAT_R16G16B16A16_USCALED" },
                                           { VK_FORMAT_R16G16B16A16_SSCALED, "VK_FORMAT_R16G16B16A16_SSCALED" },
                                           { VK_FORMAT_R16G16B16A16_UINT, "VK_FORMAT_R16G16B16A16_UINT" },
                                           { VK_FORMAT_R16G16B16A16_SINT, "VK_FORMAT_R16G16B16A16_SINT" },
                                           { VK_FORMAT_R16G16B16A16_SFLOAT, "VK_FORMAT_R16G16B16A16_SFLOAT" },
                                           { VK_FORMAT_R32_UINT, "VK_FORMAT_R32_UINT" },
                                           { VK_FORMAT_R32_SINT, "VK_FORMAT_R32_SINT" },
                                           { VK_FORMAT_R32_SFLOAT, "VK_FORMAT_R32_SFLOAT" },
                                           { VK_FORMAT_R32G32_UINT, "VK_FORMAT_R32G32_UINT" },
                                           { VK_FORMAT_R32G32_SINT, "VK_FORMAT_R32G32_SINT" },
                                           { VK_FORMAT_R32G32_SFLOAT, "VK_FORMAT_R32G32_SFLOAT" },
                                           { VK_FORMAT_R32G32B32_UINT, "VK_FORMAT_R32G32B32_UINT" },
                                           { VK_FORMAT_R32G32B32_SINT, "VK_FORMAT_R32G32B32_SINT" },
                                           { VK_FORMAT_R32G32B32_SFLOAT, "VK_FORMAT_R32G32B32_SFLOAT" },
                                           { VK_FORMAT_R32G32B32A32_UINT, "VK_FORMAT_R32G32B32A32_UINT" },
                                           { VK_FORMAT_R32G32B32A32_SINT, "VK_FORMAT_R32G32B32A32_SINT" },
                                           { VK_FORMAT_R32G32B32A32_SFLOAT, "VK_FORMAT_R32G32B32A32_SFLOAT" },
                                           { VK_FORMAT_R64_UINT, "VK_FORMAT_R64_UINT" },
                                           { VK_FORMAT_R64_SINT, "VK_FORMAT_R64_SINT" },
                                           { VK_FORMAT_R64_SFLOAT, "VK_FORMAT_R64_SFLOAT" },
                                           { VK_FORMAT_R64G64_UINT, "VK_FORMAT_R64G64_UINT" },
                                           { VK_FORMAT_R64G64_SINT, "VK_FORMAT_R64G64_SINT" },
                                           { VK_FORMAT_R64G64_SFLOAT, "VK_FORMAT_R64G64_SFLOAT" },
                                           { VK_FORMAT_R64G64B64_UINT, "VK_FORMAT_R64G64B64_UINT" },
                                           { VK_FORMAT_R64G64B64_SINT, "VK_FORMAT_R64G64B64_SINT" },
                                           { VK_FORMAT_R64G64B64_SFLOAT, "VK_FORMAT_R64G64B64_SFLOAT" },
                                           { VK_FORMAT_R64G64B64A64_UINT, "VK_FORMAT_R64G64B64A64_UINT" },
                                           { VK_FORMAT_R64G64B64A64_SINT, "VK_FORMAT_R64G64B64A64_SINT" },
                                           { VK_FORMAT_R64G64B64A64_SFLOAT, "VK_FORMAT_R64G64B64A64_SFLOAT" },
                                           { VK_FORMAT_B10G11R11_UFLOAT_PACK32, "VK_FORMAT_B10G11R11_UFLOAT_PACK32" },
                                           { VK_FORMAT_E5B9G9R9_UFLOAT_PACK32, "VK_FORMAT_E5B9G9R9_UFLOAT_PACK32" },
                                           { VK_FORMAT_D16_UNORM, "VK_FORMAT_D16_UNORM" },
                                           { VK_FORMAT_X8_D24_UNORM_PACK32, "VK_FORMAT_X8_D24_UNORM_PACK32" },
                                           { VK_FORMAT_D32_SFLOAT, "VK_FORMAT_D32_SFLOAT" },
                                           { VK_FORMAT_S8_UINT, "VK_FORMAT_S8_UINT" },
                                           { VK_FORMAT_D16_UNORM_S8_UINT, "VK_FORMAT_D16_UNORM_S8_UINT" },
                                           { VK_FORMAT_D24_UNORM_S8_UINT, "VK_FORMAT_D24_UNORM_S8_UINT" },
                                           { VK_FORMAT_D32_SFLOAT_S8_UINT, "VK_FORMAT_D32_SFLOAT_S8_UINT" },
                                           { VK_FORMAT_BC1_RGB_UNORM_BLOCK, "VK_FORMAT_BC1_RGB_UNORM_BLOCK" },
                                           { VK_FORMAT_BC1_RGB_SRGB_BLOCK, "VK_FORMAT_BC1_RGB_SRGB_BLOCK" },
                                           { VK_FORMAT_BC1_RGBA_UNORM_BLOCK, "VK_FORMAT_BC1_RGBA_UNORM_BLOCK" },
                                           { VK_FORMAT_BC1_RGBA_SRGB_BLOCK, "VK_FORMAT_BC1_RGBA_SRGB_BLOCK" },
                                           { VK_FORMAT_BC2_UNORM_BLOCK, "VK_FORMAT_BC2_UNORM_BLOCK" },
                                           { VK_FORMAT_BC2_SRGB_BLOCK, "VK_FORMAT_BC2_SRGB_BLOCK" },
                                           { VK_FORMAT_BC3_UNORM_BLOCK, "VK_FORMAT_BC3_UNORM_BLOCK" },
                                           { VK_FORMAT_BC3_SRGB_BLOCK, "VK_FORMAT_BC3_SRGB_BLOCK" },
                                           { VK_FORMAT_BC4_UNORM_BLOCK, "VK_FORMAT_BC4_UNORM_BLOCK" },
                                           { VK_FORMAT_BC4_SNORM_BLOCK, "VK_FORMAT_BC4_SNORM_BLOCK" },
                                           { VK_FORMAT_BC5_UNORM_BLOCK, "VK_FORMAT_BC5_UNORM_BLOCK" },
                                           { VK_FORMAT_BC5_SNORM_BLOCK, "VK_FORMAT_BC5_SNORM_BLOCK" },
                                           { VK_FORMAT_BC6H_UFLOAT_BLOCK, "VK_FORMAT_BC6H_UFLOAT_BLOCK" },
                                           { VK_FORMAT_BC6H_SFLOAT_BLOCK, "VK_FORMAT_BC6H_SFLOAT_BLOCK" },
                                           { VK_FORMAT_BC7_UNORM_BLOCK, "VK_FORMAT_BC7_UNORM_BLOCK" },
                                           { VK_FORMAT_BC7_SRGB_BLOCK, "VK_FORMAT_BC7_SRGB_BLOCK" },
                                           { VK_FORMAT_ETC2_R8G8B8_UNORM_BLOCK, "VK_FORMAT_ETC2_R8G8B8_UNORM_BLOCK" },
                                           { VK_FORMAT_ETC2_R8G8B8_SRGB_BLOCK, "VK_FORMAT_ETC2_R8G8B8_SRGB_BLOCK" },
                                           { VK_FORMAT_ETC2_R8G8B8A1_UNORM_BLOCK, "VK_FORMAT_ETC2_R8G8B8A1_UNORM_BLOCK" },
                                           { VK_FORMAT_ETC2_R8G8B8A1_SRGB_BLOCK, "VK_FORMAT_ETC2_R8G8B8A1_SRGB_BLOCK" },
                                           { VK_FORMAT_ETC2_R8G8B8A8_UNORM_BLOCK, "VK_FORMAT_ETC2_R8G8B8A8_UNORM_BLOCK" },
                                           { VK_FORMAT_ETC2_R8G8B8A8_SRGB_BLOCK, "VK_FORMAT_ETC2_R8G8B8A8_SRGB_BLOCK" },
                                           { VK_FORMAT_EAC_R11_UNORM_BLOCK, "VK_FORMAT_EAC_R11_UNORM_BLOCK" },
                                           { VK_FORMAT_EAC_R11_SNORM_BLOCK, "VK_FORMAT_EAC_R11_SNORM_BLOCK" },
                                           { VK_FORMAT_EAC_R11G11_UNORM_BLOCK, "VK_FORMAT_EAC_R11G11_UNORM_BLOCK" },
                                           { VK_FORMAT_EAC_R11G11_SNORM_BLOCK, "VK_FORMAT_EAC_R11G11_SNORM_BLOCK" },
                                           { VK_FORMAT_ASTC_4x4_UNORM_BLOCK, "VK_FORMAT_ASTC_4x4_UNORM_BLOCK" },
                                           { VK_FORMAT_ASTC_4x4_SRGB_BLOCK, "VK_FORMAT_ASTC_4x4_SRGB_BLOCK" },
                                           { VK_FORMAT_ASTC_5x4_UNORM_BLOCK, "VK_FORMAT_ASTC_5x4_UNORM_BLOCK" },
                                           { VK_FORMAT_ASTC_5x4_SRGB_BLOCK, "VK_FORMAT_ASTC_5x4_SRGB_BLOCK" },
                                           { VK_FORMAT_ASTC_5x5_UNORM_BLOCK, "VK_FORMAT_ASTC_5x5_UNORM_BLOCK" },
                                           { VK_FORMAT_ASTC_5x5_SRGB_BLOCK, "VK_FORMAT_ASTC_5x5_SRGB_BLOCK" },
                                           { VK_FORMAT_ASTC_6x5_UNORM_BLOCK, "VK_FORMAT_ASTC_6x5_UNORM_BLOCK" },
                                           { VK_FORMAT_ASTC_6x5_SRGB_BLOCK, "VK_FORMAT_ASTC_6x5_SRGB_BLOCK" },
                                           { VK_FORMAT_ASTC_6x6_UNORM_BLOCK, "VK_FORMAT_ASTC_6x6_UNORM_BLOCK" },
                                           { VK_FORMAT_ASTC_6x6_SRGB_BLOCK, "VK_FORMAT_ASTC_6x6_SRGB_BLOCK" },
                                           { VK_FORMAT_ASTC_8x5_UNORM_BLOCK, "VK_FORMAT_ASTC_8x5_UNORM_BLOCK" },
                                           { VK_FORMAT_ASTC_8x5_SRGB_BLOCK, "VK_FORMAT_ASTC_8x5_SRGB_BLOCK" },
                                           { VK_FORMAT_ASTC_8x6_UNORM_BLOCK, "VK_FORMAT_ASTC_8x6_UNORM_BLOCK" },
                                           { VK_FORMAT_ASTC_8x6_SRGB_BLOCK, "VK_FORMAT_ASTC_8x6_SRGB_BLOCK" },
                                           { VK_FORMAT_ASTC_8x8_UNORM_BLOCK, "VK_FORMAT_ASTC_8x8_UNORM_BLOCK" },
                                           { VK_FORMAT_ASTC_8x8_SRGB_BLOCK, "VK_FORMAT_ASTC_8x8_SRGB_BLOCK" },
                                           { VK_FORMAT_ASTC_10x5_UNORM_BLOCK, "VK_FORMAT_ASTC_10x5_UNORM_BLOCK" },
                                           { VK_FORMAT_ASTC_10x5_SRGB_BLOCK, "VK_FORMAT_ASTC_10x5_SRGB_BLOCK" },
                                           { VK_FORMAT_ASTC_10x6_UNORM_BLOCK, "VK_FORMAT_ASTC_10x6_UNORM_BLOCK" },
                                           { VK_FORMAT_ASTC_10x6_SRGB_BLOCK, "VK_FORMAT_ASTC_10x6_SRGB_BLOCK" },
                                           { VK_FORMAT_ASTC_10x8_UNORM_BLOCK, "VK_FORMAT_ASTC_10x8_UNORM_BLOCK" },
                                           { VK_FORMAT_ASTC_10x8_SRGB_BLOCK, "VK_FORMAT_ASTC_10x8_SRGB_BLOCK" },
                                           { VK_FORMAT_ASTC_10x10_UNORM_BLOCK, "VK_FORMAT_ASTC_10x10_UNORM_BLOCK" },
                                           { VK_FORMAT_ASTC_10x10_SRGB_BLOCK, "VK_FORMAT_ASTC_10x10_SRGB_BLOCK" },
                                           { VK_FORMAT_ASTC_12x10_UNORM_BLOCK, "VK_FORMAT_ASTC_12x10_UNORM_BLOCK" },
                                           { VK_FORMAT_ASTC_12x10_SRGB_BLOCK, "VK_FORMAT_ASTC_12x10_SRGB_BLOCK" },
                                           { VK_FORMAT_ASTC_12x12_UNORM_BLOCK, "VK_FORMAT_ASTC_12x12_UNORM_BLOCK" },
                                           { VK_FORMAT_ASTC_12x12_SRGB_BLOCK, "VK_FORMAT_ASTC_12x12_SRGB_BLOCK" },
                                           { VK_FORMAT_G8B8G8R8_422_UNORM, "VK_FORMAT_G8B8G8R8_422_UNORM" },
                                           { VK_FORMAT_B8G8R8G8_422_UNORM, "VK_FORMAT_B8G8R8G8_422_UNORM" },
                                           { VK_FORMAT_G8_B8_R8_3PLANE_420_UNORM, "VK_FORMAT_G8_B8_R8_3PLANE_420_UNORM" },
                                           { VK_FORMAT_G8_B8R8_2PLANE_420_UNORM, "VK_FORMAT_G8_B8R8_2PLANE_420_UNORM" },
                                           { VK_FORMAT_G8_B8_R8_3PLANE_422_UNORM, "VK_FORMAT_G8_B8_R8_3PLANE_422_UNORM" },
                                           { VK_FORMAT_G8_B8R8_2PLANE_422_UNORM, "VK_FORMAT_G8_B8R8_2PLANE_422_UNORM" },
                                           { VK_FORMAT_G8_B8_R8_3PLANE_444_UNORM, "VK_FORMAT_G8_B8_R8_3PLANE_444_UNORM" },
                                           { VK_FORMAT_R10X6_UNORM_PACK16, "VK_FORMAT_R10X6_UNORM_PACK16" },
                                           { VK_FORMAT_R10X6G10X6_UNORM_2PACK16, "VK_FORMAT_R10X6G10X6_UNORM_2PACK16" },
                                           { VK_FORMAT_R10X6G10X6B10X6A10X6_UNORM_4PACK16, "VK_FORMAT_R10X6G10X6B10X6A10X6_UNORM_4PACK16" },
                                           { VK_FORMAT_G10X6B10X6G10X6R10X6_422_UNORM_4PACK16, "VK_FORMAT_G10X6B10X6G10X6R10X6_422_UNORM_4PACK16" },
                                           { VK_FORMAT_B10X6G10X6R10X6G10X6_422_UNORM_4PACK16, "VK_FORMAT_B10X6G10X6R10X6G10X6_422_UNORM_4PACK16" },
                                           { VK_FORMAT_G10X6_B10X6_R10X6_3PLANE_420_UNORM_3PACK16, "VK_FORMAT_G10X6_B10X6_R10X6_3PLANE_420_UNORM_3PACK16" },
                                           { VK_FORMAT_G10X6_B10X6R10X6_2PLANE_420_UNORM_3PACK16, "VK_FORMAT_G10X6_B10X6R10X6_2PLANE_420_UNORM_3PACK16" },
                                           { VK_FORMAT_G10X6_B10X6_R10X6_3PLANE_422_UNORM_3PACK16, "VK_FORMAT_G10X6_B10X6_R10X6_3PLANE_422_UNORM_3PACK16" },
                                           { VK_FORMAT_G10X6_B10X6R10X6_2PLANE_422_UNORM_3PACK16, "VK_FORMAT_G10X6_B10X6R10X6_2PLANE_422_UNORM_3PACK16" },
                                           { VK_FORMAT_G10X6_B10X6_R10X6_3PLANE_444_UNORM_3PACK16, "VK_FORMAT_G10X6_B10X6_R10X6_3PLANE_444_UNORM_3PACK16" },
                                           { VK_FORMAT_R12X4_UNORM_PACK16, "VK_FORMAT_R12X4_UNORM_PACK16" },
                                           { VK_FORMAT_R12X4G12X4_UNORM_2PACK16, "VK_FORMAT_R12X4G12X4_UNORM_2PACK16" },
                                           { VK_FORMAT_R12X4G12X4B12X4A12X4_UNORM_4PACK16, "VK_FORMAT_R12X4G12X4B12X4A12X4_UNORM_4PACK16" },
                                           { VK_FORMAT_G12X4B12X4G12X4R12X4_422_UNORM_4PACK16, "VK_FORMAT_G12X4B12X4G12X4R12X4_422_UNORM_4PACK16" },
                                           { VK_FORMAT_B12X4G12X4R12X4G12X4_422_UNORM_4PACK16, "VK_FORMAT_B12X4G12X4R12X4G12X4_422_UNORM_4PACK16" },
                                           { VK_FORMAT_G12X4_B12X4_R12X4_3PLANE_420_UNORM_3PACK16, "VK_FORMAT_G12X4_B12X4_R12X4_3PLANE_420_UNORM_3PACK16" },
                                           { VK_FORMAT_G12X4_B12X4R12X4_2PLANE_420_UNORM_3PACK16, "VK_FORMAT_G12X4_B12X4R12X4_2PLANE_420_UNORM_3PACK16" },
                                           { VK_FORMAT_G12X4_B12X4_R12X4_3PLANE_422_UNORM_3PACK16, "VK_FORMAT_G12X4_B12X4_R12X4_3PLANE_422_UNORM_3PACK16" },
                                           { VK_FORMAT_G12X4_B12X4R12X4_2PLANE_422_UNORM_3PACK16, "VK_FORMAT_G12X4_B12X4R12X4_2PLANE_422_UNORM_3PACK16" },
                                           { VK_FORMAT_G12X4_B12X4_R12X4_3PLANE_444_UNORM_3PACK16, "VK_FORMAT_G12X4_B12X4_R12X4_3PLANE_444_UNORM_3PACK16" },
                                           { VK_FORMAT_G16B16G16R16_422_UNORM, "VK_FORMAT_G16B16G16R16_422_UNORM" },
                                           { VK_FORMAT_B16G16R16G16_422_UNORM, "VK_FORMAT_B16G16R16G16_422_UNORM" },
                                           { VK_FORMAT_G16_B16_R16_3PLANE_420_UNORM, "VK_FORMAT_G16_B16_R16_3PLANE_420_UNORM" },
                                           { VK_FORMAT_G16_B16R16_2PLANE_420_UNORM, "VK_FORMAT_G16_B16R16_2PLANE_420_UNORM" },
                                           { VK_FORMAT_G16_B16_R16_3PLANE_422_UNORM, "VK_FORMAT_G16_B16_R16_3PLANE_422_UNORM" },
                                           { VK_FORMAT_G16_B16R16_2PLANE_422_UNORM, "VK_FORMAT_G16_B16R16_2PLANE_422_UNORM" },
                                           { VK_FORMAT_G16_B16_R16_3PLANE_444_UNORM, "VK_FORMAT_G16_B16_R16_3PLANE_444_UNORM" },
                                           { VK_FORMAT_G8_B8R8_2PLANE_444_UNORM, "VK_FORMAT_G8_B8R8_2PLANE_444_UNORM" },
                                           { VK_FORMAT_G10X6_B10X6R10X6_2PLANE_444_UNORM_3PACK16, "VK_FORMAT_G10X6_B10X6R10X6_2PLANE_444_UNORM_3PACK16" },
                                           { VK_FORMAT_G12X4_B12X4R12X4_2PLANE_444_UNORM_3PACK16, "VK_FORMAT_G12X4_B12X4R12X4_2PLANE_444_UNORM_3PACK16" },
                                           { VK_FORMAT_G16_B16R16_2PLANE_444_UNORM, "VK_FORMAT_G16_B16R16_2PLANE_444_UNORM" },
                                           { VK_FORMAT_A4R4G4B4_UNORM_PACK16, "VK_FORMAT_A4R4G4B4_UNORM_PACK16" },
                                           { VK_FORMAT_A4B4G4R4_UNORM_PACK16, "VK_FORMAT_A4B4G4R4_UNORM_PACK16" },
                                           { VK_FORMAT_ASTC_4x4_SFLOAT_BLOCK, "VK_FORMAT_ASTC_4x4_SFLOAT_BLOCK" },
                                           { VK_FORMAT_ASTC_5x4_SFLOAT_BLOCK, "VK_FORMAT_ASTC_5x4_SFLOAT_BLOCK" },
                                           { VK_FORMAT_ASTC_5x5_SFLOAT_BLOCK, "VK_FORMAT_ASTC_5x5_SFLOAT_BLOCK" },
                                           { VK_FORMAT_ASTC_6x5_SFLOAT_BLOCK, "VK_FORMAT_ASTC_6x5_SFLOAT_BLOCK" },
                                           { VK_FORMAT_ASTC_6x6_SFLOAT_BLOCK, "VK_FORMAT_ASTC_6x6_SFLOAT_BLOCK" },
                                           { VK_FORMAT_ASTC_8x5_SFLOAT_BLOCK, "VK_FORMAT_ASTC_8x5_SFLOAT_BLOCK" },
                                           { VK_FORMAT_ASTC_8x6_SFLOAT_BLOCK, "VK_FORMAT_ASTC_8x6_SFLOAT_BLOCK" },
                                           { VK_FORMAT_ASTC_8x8_SFLOAT_BLOCK, "VK_FORMAT_ASTC_8x8_SFLOAT_BLOCK" },
                                           { VK_FORMAT_ASTC_10x5_SFLOAT_BLOCK, "VK_FORMAT_ASTC_10x5_SFLOAT_BLOCK" },
                                           { VK_FORMAT_ASTC_10x6_SFLOAT_BLOCK, "VK_FORMAT_ASTC_10x6_SFLOAT_BLOCK" },
                                           { VK_FORMAT_ASTC_10x8_SFLOAT_BLOCK, "VK_FORMAT_ASTC_10x8_SFLOAT_BLOCK" },
                                           { VK_FORMAT_ASTC_10x10_SFLOAT_BLOCK, "VK_FORMAT_ASTC_10x10_SFLOAT_BLOCK" },
                                           { VK_FORMAT_ASTC_12x10_SFLOAT_BLOCK, "VK_FORMAT_ASTC_12x10_SFLOAT_BLOCK" },
                                           { VK_FORMAT_ASTC_12x12_SFLOAT_BLOCK, "VK_FORMAT_ASTC_12x12_SFLOAT_BLOCK" },
                                           { VK_FORMAT_PVRTC1_2BPP_UNORM_BLOCK_IMG, "VK_FORMAT_PVRTC1_2BPP_UNORM_BLOCK_IMG" },
                                           { VK_FORMAT_PVRTC1_4BPP_UNORM_BLOCK_IMG, "VK_FORMAT_PVRTC1_4BPP_UNORM_BLOCK_IMG" },
                                           { VK_FORMAT_PVRTC2_2BPP_UNORM_BLOCK_IMG, "VK_FORMAT_PVRTC2_2BPP_UNORM_BLOCK_IMG" },
                                           { VK_FORMAT_PVRTC2_4BPP_UNORM_BLOCK_IMG, "VK_FORMAT_PVRTC2_4BPP_UNORM_BLOCK_IMG" },
                                           { VK_FORMAT_PVRTC1_2BPP_SRGB_BLOCK_IMG, "VK_FORMAT_PVRTC1_2BPP_SRGB_BLOCK_IMG" },
                                           { VK_FORMAT_PVRTC1_4BPP_SRGB_BLOCK_IMG, "VK_FORMAT_PVRTC1_4BPP_SRGB_BLOCK_IMG" },
                                           { VK_FORMAT_PVRTC2_2BPP_SRGB_BLOCK_IMG, "VK_FORMAT_PVRTC2_2BPP_SRGB_BLOCK_IMG" },
                                           { VK_FORMAT_PVRTC2_4BPP_SRGB_BLOCK_IMG, "VK_FORMAT_PVRTC2_4BPP_SRGB_BLOCK_IMG" },
                                           //    {VK_FORMAT_R16G16_SFIXED5_NV, "VK_FORMAT_R16G16_SFIXED5_NV"},
                                           { VK_FORMAT_A1B5G5R5_UNORM_PACK16_KHR, "VK_FORMAT_A1B5G5R5_UNORM_PACK16_KHR" },
                                           { VK_FORMAT_A8_UNORM_KHR, "VK_FORMAT_A8_UNORM_KHR" },
                                           { VK_FORMAT_ASTC_4x4_SFLOAT_BLOCK_EXT, "VK_FORMAT_ASTC_4x4_SFLOAT_BLOCK_EXT" },
                                           { VK_FORMAT_ASTC_5x4_SFLOAT_BLOCK_EXT, "VK_FORMAT_ASTC_5x4_SFLOAT_BLOCK_EXT" },
                                           { VK_FORMAT_ASTC_5x5_SFLOAT_BLOCK_EXT, "VK_FORMAT_ASTC_5x5_SFLOAT_BLOCK_EXT" },
                                           { VK_FORMAT_ASTC_6x5_SFLOAT_BLOCK_EXT, "VK_FORMAT_ASTC_6x5_SFLOAT_BLOCK_EXT" },
                                           { VK_FORMAT_ASTC_6x6_SFLOAT_BLOCK_EXT, "VK_FORMAT_ASTC_6x6_SFLOAT_BLOCK_EXT" },
                                           { VK_FORMAT_ASTC_8x5_SFLOAT_BLOCK_EXT, "VK_FORMAT_ASTC_8x5_SFLOAT_BLOCK_EXT" },
                                           { VK_FORMAT_ASTC_8x6_SFLOAT_BLOCK_EXT, "VK_FORMAT_ASTC_8x6_SFLOAT_BLOCK_EXT" },
                                           { VK_FORMAT_ASTC_8x8_SFLOAT_BLOCK_EXT, "VK_FORMAT_ASTC_8x8_SFLOAT_BLOCK_EXT" },
                                           { VK_FORMAT_ASTC_10x5_SFLOAT_BLOCK_EXT, "VK_FORMAT_ASTC_10x5_SFLOAT_BLOCK_EXT" },
                                           { VK_FORMAT_ASTC_10x6_SFLOAT_BLOCK_EXT, "VK_FORMAT_ASTC_10x6_SFLOAT_BLOCK_EXT" },
                                           { VK_FORMAT_ASTC_10x8_SFLOAT_BLOCK_EXT, "VK_FORMAT_ASTC_10x8_SFLOAT_BLOCK_EXT" },
                                           { VK_FORMAT_ASTC_10x10_SFLOAT_BLOCK_EXT, "VK_FORMAT_ASTC_10x10_SFLOAT_BLOCK_EXT" },
                                           { VK_FORMAT_ASTC_12x10_SFLOAT_BLOCK_EXT, "VK_FORMAT_ASTC_12x10_SFLOAT_BLOCK_EXT" },
                                           { VK_FORMAT_ASTC_12x12_SFLOAT_BLOCK_EXT, "VK_FORMAT_ASTC_12x12_SFLOAT_BLOCK_EXT" },
                                           { VK_FORMAT_G8B8G8R8_422_UNORM_KHR, "VK_FORMAT_G8B8G8R8_422_UNORM_KHR" },
                                           { VK_FORMAT_B8G8R8G8_422_UNORM_KHR, "VK_FORMAT_B8G8R8G8_422_UNORM_KHR" },
                                           { VK_FORMAT_G8_B8_R8_3PLANE_420_UNORM_KHR, "VK_FORMAT_G8_B8_R8_3PLANE_420_UNORM_KHR" },
                                           { VK_FORMAT_G8_B8R8_2PLANE_420_UNORM_KHR, "VK_FORMAT_G8_B8R8_2PLANE_420_UNORM_KHR" },
                                           { VK_FORMAT_G8_B8_R8_3PLANE_422_UNORM_KHR, "VK_FORMAT_G8_B8_R8_3PLANE_422_UNORM_KHR" },
                                           { VK_FORMAT_G8_B8R8_2PLANE_422_UNORM_KHR, "VK_FORMAT_G8_B8R8_2PLANE_422_UNORM_KHR" },
                                           { VK_FORMAT_G8_B8_R8_3PLANE_444_UNORM_KHR, "VK_FORMAT_G8_B8_R8_3PLANE_444_UNORM_KHR" },
                                           { VK_FORMAT_R10X6_UNORM_PACK16_KHR, "VK_FORMAT_R10X6_UNORM_PACK16_KHR" },
                                           { VK_FORMAT_R10X6G10X6_UNORM_2PACK16_KHR, "VK_FORMAT_R10X6G10X6_UNORM_2PACK16_KHR" },
                                           { VK_FORMAT_R10X6G10X6B10X6A10X6_UNORM_4PACK16_KHR, "VK_FORMAT_R10X6G10X6B10X6A10X6_UNORM_4PACK16_KHR" },
                                           { VK_FORMAT_G10X6B10X6G10X6R10X6_422_UNORM_4PACK16_KHR, "VK_FORMAT_G10X6B10X6G10X6R10X6_422_UNORM_4PACK16_KHR" },
                                           { VK_FORMAT_B10X6G10X6R10X6G10X6_422_UNORM_4PACK16_KHR, "VK_FORMAT_B10X6G10X6R10X6G10X6_422_UNORM_4PACK16_KHR" },
                                           { VK_FORMAT_G10X6_B10X6_R10X6_3PLANE_420_UNORM_3PACK16_KHR, "VK_FORMAT_G10X6_B10X6_R10X6_3PLANE_420_UNORM_3PACK16_KHR" },
                                           { VK_FORMAT_G10X6_B10X6R10X6_2PLANE_420_UNORM_3PACK16_KHR, "VK_FORMAT_G10X6_B10X6R10X6_2PLANE_420_UNORM_3PACK16_KHR" },
                                           { VK_FORMAT_G10X6_B10X6_R10X6_3PLANE_422_UNORM_3PACK16_KHR, "VK_FORMAT_G10X6_B10X6_R10X6_3PLANE_422_UNORM_3PACK16_KHR" },
                                           { VK_FORMAT_G10X6_B10X6R10X6_2PLANE_422_UNORM_3PACK16_KHR, "VK_FORMAT_G10X6_B10X6R10X6_2PLANE_422_UNORM_3PACK16_KHR" },
                                           { VK_FORMAT_G10X6_B10X6_R10X6_3PLANE_444_UNORM_3PACK16_KHR, "VK_FORMAT_G10X6_B10X6_R10X6_3PLANE_444_UNORM_3PACK16_KHR" },
                                           { VK_FORMAT_R12X4_UNORM_PACK16_KHR, "VK_FORMAT_R12X4_UNORM_PACK16_KHR" },
                                           { VK_FORMAT_R12X4G12X4_UNORM_2PACK16_KHR, "VK_FORMAT_R12X4G12X4_UNORM_2PACK16_KHR" },
                                           { VK_FORMAT_R12X4G12X4B12X4A12X4_UNORM_4PACK16_KHR, "VK_FORMAT_R12X4G12X4B12X4A12X4_UNORM_4PACK16_KHR" },
                                           { VK_FORMAT_G12X4B12X4G12X4R12X4_422_UNORM_4PACK16_KHR, "VK_FORMAT_G12X4B12X4G12X4R12X4_422_UNORM_4PACK16_KHR" },
                                           { VK_FORMAT_B12X4G12X4R12X4G12X4_422_UNORM_4PACK16_KHR, "VK_FORMAT_B12X4G12X4R12X4G12X4_422_UNORM_4PACK16_KHR" },
                                           { VK_FORMAT_G12X4_B12X4_R12X4_3PLANE_420_UNORM_3PACK16_KHR, "VK_FORMAT_G12X4_B12X4_R12X4_3PLANE_420_UNORM_3PACK16_KHR" },
                                           { VK_FORMAT_G12X4_B12X4R12X4_2PLANE_420_UNORM_3PACK16_KHR, "VK_FORMAT_G12X4_B12X4R12X4_2PLANE_420_UNORM_3PACK16_KHR" },
                                           { VK_FORMAT_G12X4_B12X4_R12X4_3PLANE_422_UNORM_3PACK16_KHR, "VK_FORMAT_G12X4_B12X4_R12X4_3PLANE_422_UNORM_3PACK16_KHR" },
                                           { VK_FORMAT_G12X4_B12X4R12X4_2PLANE_422_UNORM_3PACK16_KHR, "VK_FORMAT_G12X4_B12X4R12X4_2PLANE_422_UNORM_3PACK16_KHR" },
                                           { VK_FORMAT_G12X4_B12X4_R12X4_3PLANE_444_UNORM_3PACK16_KHR, "VK_FORMAT_G12X4_B12X4_R12X4_3PLANE_444_UNORM_3PACK16_KHR" },
                                           { VK_FORMAT_G16B16G16R16_422_UNORM_KHR, "VK_FORMAT_G16B16G16R16_422_UNORM_KHR" },
                                           { VK_FORMAT_B16G16R16G16_422_UNORM_KHR, "VK_FORMAT_B16G16R16G16_422_UNORM_KHR" },
                                           { VK_FORMAT_G16_B16_R16_3PLANE_420_UNORM_KHR, "VK_FORMAT_G16_B16_R16_3PLANE_420_UNORM_KHR" },
                                           { VK_FORMAT_G16_B16R16_2PLANE_420_UNORM_KHR, "VK_FORMAT_G16_B16R16_2PLANE_420_UNORM_KHR" },
                                           { VK_FORMAT_G16_B16_R16_3PLANE_422_UNORM_KHR, "VK_FORMAT_G16_B16_R16_3PLANE_422_UNORM_KHR" },
                                           { VK_FORMAT_G16_B16R16_2PLANE_422_UNORM_KHR, "VK_FORMAT_G16_B16R16_2PLANE_422_UNORM_KHR" },
                                           { VK_FORMAT_G16_B16_R16_3PLANE_444_UNORM_KHR, "VK_FORMAT_G16_B16_R16_3PLANE_444_UNORM_KHR" },
                                           { VK_FORMAT_G8_B8R8_2PLANE_444_UNORM_EXT, "VK_FORMAT_G8_B8R8_2PLANE_444_UNORM_EXT" },
                                           { VK_FORMAT_G10X6_B10X6R10X6_2PLANE_444_UNORM_3PACK16_EXT, "VK_FORMAT_G10X6_B10X6R10X6_2PLANE_444_UNORM_3PACK16_EXT" },
                                           { VK_FORMAT_G12X4_B12X4R12X4_2PLANE_444_UNORM_3PACK16_EXT, "VK_FORMAT_G12X4_B12X4R12X4_2PLANE_444_UNORM_3PACK16_EXT" },
                                           { VK_FORMAT_G16_B16R16_2PLANE_444_UNORM_EXT, "VK_FORMAT_G16_B16R16_2PLANE_444_UNORM_EXT" },
                                           { VK_FORMAT_A4R4G4B4_UNORM_PACK16_EXT, "VK_FORMAT_A4R4G4B4_UNORM_PACK16_EXT" },
                                           { VK_FORMAT_A4B4G4R4_UNORM_PACK16_EXT, "VK_FORMAT_A4B4G4R4_UNORM_PACK16_EXT" },
                                           { VK_FORMAT_R16G16_S10_5_NV, "VK_FORMAT_R16G16_S10_5_NV" },
                                       })

NLOHMANN_JSON_SERIALIZE_ENUM(VkVertexInputRate, { { VK_VERTEX_INPUT_RATE_VERTEX, "VK_VERTEX_INPUT_RATE_VERTEX" }, { VK_VERTEX_INPUT_RATE_INSTANCE, "VK_VERTEX_INPUT_RATE_INSTANCE" } })

NLOHMANN_JSON_SERIALIZE_ENUM(VkPrimitiveTopology, { { VK_PRIMITIVE_TOPOLOGY_POINT_LIST, "VK_PRIMITIVE_TOPOLOGY_POINT_LIST" }, { VK_PRIMITIVE_TOPOLOGY_LINE_LIST, "VK_PRIMITIVE_TOPOLOGY_LINE_LIST" }, { VK_PRIMITIVE_TOPOLOGY_LINE_STRIP, "VK_PRIMITIVE_TOPOLOGY_LINE_STRIP" }, { VK_PRIMITIVE_TOPOLOGY_TRIANGLE_LIST, "VK_PRIMITIVE_TOPOLOGY_TRIANGLE_LIST" }, { VK_PRIMITIVE_TOPOLOGY_TRIANGLE_STRIP, "VK_PRIMITIVE_TOPOLOGY_TRIANGLE_STRIP" }, { VK_PRIMITIVE_TOPOLOGY_TRIANGLE_FAN, "VK_PRIMITIVE_TOPOLOGY_TRIANGLE_FAN" }, { VK_PRIMITIVE_TOPOLOGY_LINE_LIST_WITH_ADJACENCY, "VK_PRIMITIVE_TOPOLOGY_LINE_LIST_WITH_ADJACENCY" }, { VK_PRIMITIVE_TOPOLOGY_LINE_STRIP_WITH_ADJACENCY, "VK_PRIMITIVE_TOPOLOGY_LINE_STRIP_WITH_ADJACENCY" }, { VK_PRIMITIVE_TOPOLOGY_TRIANGLE_LIST_WITH_ADJACENCY, "VK_PRIMITIVE_TOPOLOGY_TRIANGLE_LIST_WITH_ADJACENCY" }, { VK_PRIMITIVE_TOPOLOGY_TRIANGLE_STRIP_WITH_ADJACENCY, "VK_PRIMITIVE_TOPOLOGY_TRIANGLE_STRIP_WITH_ADJACENCY" }, { VK_PRIMITIVE_TOPOLOGY_PATCH_LIST, "VK_PRIMITIVE_TOPOLOGY_PATCH_LIST" } })

NLOHMANN_JSON_SERIALIZE_ENUM(VkPolygonMode, {
                                                { VK_POLYGON_MODE_FILL, "VK_POLYGON_MODE_FILL" },
                                                { VK_POLYGON_MODE_LINE, "VK_POLYGON_MODE_LINE" },
                                                { VK_POLYGON_MODE_POINT, "VK_POLYGON_MODE_POINT" },
                                                { VK_POLYGON_MODE_FILL_RECTANGLE_NV, "VK_POLYGON_MODE_FILL_RECTANGLE_NV" },
                                            })

NLOHMANN_JSON_SERIALIZE_ENUM(VkFrontFace, {
                                              { VK_FRONT_FACE_COUNTER_CLOCKWISE, "VK_FRONT_FACE_COUNTER_CLOCKWISE" },
                                              { VK_FRONT_FACE_CLOCKWISE, "VK_FRONT_FACE_CLOCKWISE" },
                                          })

NLOHMANN_JSON_SERIALIZE_ENUM(VkCompareOp, {
                                              { VK_COMPARE_OP_NEVER, "VK_COMPARE_OP_NEVER" },
                                              { VK_COMPARE_OP_LESS, "VK_COMPARE_OP_LESS" },
                                              { VK_COMPARE_OP_EQUAL, "VK_COMPARE_OP_EQUAL" },
                                              { VK_COMPARE_OP_LESS_OR_EQUAL, "VK_COMPARE_OP_LESS_OR_EQUAL" },
                                              { VK_COMPARE_OP_GREATER, "VK_COMPARE_OP_GREATER" },
                                              { VK_COMPARE_OP_NOT_EQUAL, "VK_COMPARE_OP_NOT_EQUAL" },
                                              { VK_COMPARE_OP_GREATER_OR_EQUAL, "VK_COMPARE_OP_GREATER_OR_EQUAL" },
                                              { VK_COMPARE_OP_ALWAYS, "VK_COMPARE_OP_ALWAYS" },
                                          })

NLOHMANN_JSON_SERIALIZE_ENUM(VkStencilOp, {
                                              { VK_STENCIL_OP_KEEP, "VK_STENCIL_OP_KEEP" },
                                              { VK_STENCIL_OP_ZERO, "VK_STENCIL_OP_ZERO" },
                                              { VK_STENCIL_OP_REPLACE, "VK_STENCIL_OP_REPLACE" },
                                              { VK_STENCIL_OP_INCREMENT_AND_CLAMP, "VK_STENCIL_OP_INCREMENT_AND_CLAMP" },
                                              { VK_STENCIL_OP_DECREMENT_AND_CLAMP, "VK_STENCIL_OP_DECREMENT_AND_CLAMP" },
                                              { VK_STENCIL_OP_INVERT, "VK_STENCIL_OP_INVERT" },
                                              { VK_STENCIL_OP_INCREMENT_AND_WRAP, "VK_STENCIL_OP_INCREMENT_AND_WRAP" },
                                              { VK_STENCIL_OP_DECREMENT_AND_WRAP, "VK_STENCIL_OP_DECREMENT_AND_WRAP" },
                                          })

NLOHMANN_JSON_SERIALIZE_ENUM(VkLogicOp, {
                                            { VK_LOGIC_OP_CLEAR, "VK_LOGIC_OP_CLEAR" },
                                            { VK_LOGIC_OP_AND, "VK_LOGIC_OP_AND" },
                                            { VK_LOGIC_OP_AND_REVERSE, "VK_LOGIC_OP_AND_REVERSE" },
                                            { VK_LOGIC_OP_COPY, "VK_LOGIC_OP_COPY" },
                                            { VK_LOGIC_OP_AND_INVERTED, "VK_LOGIC_OP_AND_INVERTED" },
                                            { VK_LOGIC_OP_NO_OP, "VK_LOGIC_OP_NO_OP" },
                                            { VK_LOGIC_OP_XOR, "VK_LOGIC_OP_XOR" },
                                            { VK_LOGIC_OP_OR, "VK_LOGIC_OP_OR" },
                                            { VK_LOGIC_OP_NOR, "VK_LOGIC_OP_NOR" },
                                            { VK_LOGIC_OP_EQUIVALENT, "VK_LOGIC_OP_EQUIVALENT" },
                                            { VK_LOGIC_OP_INVERT, "VK_LOGIC_OP_INVERT" },
                                            { VK_LOGIC_OP_OR_REVERSE, "VK_LOGIC_OP_OR_REVERSE" },
                                            { VK_LOGIC_OP_COPY_INVERTED, "VK_LOGIC_OP_COPY_INVERTED" },
                                            { VK_LOGIC_OP_OR_INVERTED, "VK_LOGIC_OP_OR_INVERTED" },
                                            { VK_LOGIC_OP_NAND, "VK_LOGIC_OP_NAND" },
                                            { VK_LOGIC_OP_SET, "VK_LOGIC_OP_SET" },
                                        })

NLOHMANN_JSON_SERIALIZE_ENUM(VkBlendFactor, {
                                                { VK_BLEND_FACTOR_ZERO, "VK_BLEND_FACTOR_ZERO" },
                                                { VK_BLEND_FACTOR_ONE, "VK_BLEND_FACTOR_ONE" },
                                                { VK_BLEND_FACTOR_SRC_COLOR, "VK_BLEND_FACTOR_SRC_COLOR" },
                                                { VK_BLEND_FACTOR_ONE_MINUS_SRC_COLOR, "VK_BLEND_FACTOR_ONE_MINUS_SRC_COLOR" },
                                                { VK_BLEND_FACTOR_DST_COLOR, "VK_BLEND_FACTOR_DST_COLOR" },
                                                { VK_BLEND_FACTOR_ONE_MINUS_DST_COLOR, "VK_BLEND_FACTOR_ONE_MINUS_DST_COLOR" },
                                                { VK_BLEND_FACTOR_SRC_ALPHA, "VK_BLEND_FACTOR_SRC_ALPHA" },
                                                { VK_BLEND_FACTOR_ONE_MINUS_SRC_ALPHA, "VK_BLEND_FACTOR_ONE_MINUS_SRC_ALPHA" },
                                                { VK_BLEND_FACTOR_DST_ALPHA, "VK_BLEND_FACTOR_DST_ALPHA" },
                                                { VK_BLEND_FACTOR_ONE_MINUS_DST_ALPHA, "VK_BLEND_FACTOR_ONE_MINUS_DST_ALPHA" },
                                                { VK_BLEND_FACTOR_CONSTANT_COLOR, "VK_BLEND_FACTOR_CONSTANT_COLOR" },
                                                { VK_BLEND_FACTOR_ONE_MINUS_CONSTANT_COLOR, "VK_BLEND_FACTOR_ONE_MINUS_CONSTANT_COLOR" },
                                                { VK_BLEND_FACTOR_CONSTANT_ALPHA, "VK_BLEND_FACTOR_CONSTANT_ALPHA" },
                                                { VK_BLEND_FACTOR_ONE_MINUS_CONSTANT_ALPHA, "VK_BLEND_FACTOR_ONE_MINUS_CONSTANT_ALPHA" },
                                                { VK_BLEND_FACTOR_SRC_ALPHA_SATURATE, "VK_BLEND_FACTOR_SRC_ALPHA_SATURATE" },
                                                { VK_BLEND_FACTOR_SRC1_COLOR, "VK_BLEND_FACTOR_SRC1_COLOR" },
                                                { VK_BLEND_FACTOR_ONE_MINUS_SRC1_COLOR, "VK_BLEND_FACTOR_ONE_MINUS_SRC1_COLOR" },
                                                { VK_BLEND_FACTOR_SRC1_ALPHA, "VK_BLEND_FACTOR_SRC1_ALPHA" },
                                                { VK_BLEND_FACTOR_ONE_MINUS_SRC1_ALPHA, "VK_BLEND_FACTOR_ONE_MINUS_SRC1_ALPHA" },
                                            })

NLOHMANN_JSON_SERIALIZE_ENUM(VkBlendOp, {
                                            { VK_BLEND_OP_ADD, "VK_BLEND_OP_ADD" },
                                            { VK_BLEND_OP_SUBTRACT, "VK_BLEND_OP_SUBTRACT" },
                                            { VK_BLEND_OP_REVERSE_SUBTRACT, "VK_BLEND_OP_REVERSE_SUBTRACT" },
                                            { VK_BLEND_OP_MIN, "VK_BLEND_OP_MIN" },
                                            { VK_BLEND_OP_MAX, "VK_BLEND_OP_MAX" },
                                            { VK_BLEND_OP_ZERO_EXT, "VK_BLEND_OP_ZERO_EXT" },
                                            { VK_BLEND_OP_SRC_EXT, "VK_BLEND_OP_SRC_EXT" },
                                            { VK_BLEND_OP_DST_EXT, "VK_BLEND_OP_DST_EXT" },
                                            { VK_BLEND_OP_SRC_OVER_EXT, "VK_BLEND_OP_SRC_OVER_EXT" },
                                            { VK_BLEND_OP_DST_OVER_EXT, "VK_BLEND_OP_DST_OVER_EXT" },
                                            { VK_BLEND_OP_SRC_IN_EXT, "VK_BLEND_OP_SRC_IN_EXT" },
                                            { VK_BLEND_OP_DST_IN_EXT, "VK_BLEND_OP_DST_IN_EXT" },
                                            { VK_BLEND_OP_SRC_OUT_EXT, "VK_BLEND_OP_SRC_OUT_EXT" },
                                            { VK_BLEND_OP_DST_OUT_EXT, "VK_BLEND_OP_DST_OUT_EXT" },
                                            { VK_BLEND_OP_SRC_ATOP_EXT, "VK_BLEND_OP_SRC_ATOP_EXT" },
                                            { VK_BLEND_OP_DST_ATOP_EXT, "VK_BLEND_OP_DST_ATOP_EXT" },
                                            { VK_BLEND_OP_XOR_EXT, "VK_BLEND_OP_XOR_EXT" },
                                            { VK_BLEND_OP_MULTIPLY_EXT, "VK_BLEND_OP_MULTIPLY_EXT" },
                                            { VK_BLEND_OP_SCREEN_EXT, "VK_BLEND_OP_SCREEN_EXT" },
                                            { VK_BLEND_OP_OVERLAY_EXT, "VK_BLEND_OP_OVERLAY_EXT" },
                                            { VK_BLEND_OP_DARKEN_EXT, "VK_BLEND_OP_DARKEN_EXT" },
                                            { VK_BLEND_OP_LIGHTEN_EXT, "VK_BLEND_OP_LIGHTEN_EXT" },
                                            { VK_BLEND_OP_COLORDODGE_EXT, "VK_BLEND_OP_COLORDODGE_EXT" },
                                            { VK_BLEND_OP_COLORBURN_EXT, "VK_BLEND_OP_COLORBURN_EXT" },
                                            { VK_BLEND_OP_HARDLIGHT_EXT, "VK_BLEND_OP_HARDLIGHT_EXT" },
                                            { VK_BLEND_OP_SOFTLIGHT_EXT, "VK_BLEND_OP_SOFTLIGHT_EXT" },
                                            { VK_BLEND_OP_DIFFERENCE_EXT, "VK_BLEND_OP_DIFFERENCE_EXT" },
                                            { VK_BLEND_OP_EXCLUSION_EXT, "VK_BLEND_OP_EXCLUSION_EXT" },
                                            { VK_BLEND_OP_INVERT_EXT, "VK_BLEND_OP_INVERT_EXT" },
                                            { VK_BLEND_OP_INVERT_RGB_EXT, "VK_BLEND_OP_INVERT_RGB_EXT" },
                                            { VK_BLEND_OP_LINEARDODGE_EXT, "VK_BLEND_OP_LINEARDODGE_EXT" },
                                            { VK_BLEND_OP_LINEARBURN_EXT, "VK_BLEND_OP_LINEARBURN_EXT" },
                                            { VK_BLEND_OP_VIVIDLIGHT_EXT, "VK_BLEND_OP_VIVIDLIGHT_EXT" },
                                            { VK_BLEND_OP_LINEARLIGHT_EXT, "VK_BLEND_OP_LINEARLIGHT_EXT" },
                                            { VK_BLEND_OP_PINLIGHT_EXT, "VK_BLEND_OP_PINLIGHT_EXT" },
                                            { VK_BLEND_OP_HARDMIX_EXT, "VK_BLEND_OP_HARDMIX_EXT" },
                                            { VK_BLEND_OP_HSL_HUE_EXT, "VK_BLEND_OP_HSL_HUE_EXT" },
                                            { VK_BLEND_OP_HSL_SATURATION_EXT, "VK_BLEND_OP_HSL_SATURATION_EXT" },
                                            { VK_BLEND_OP_HSL_COLOR_EXT, "VK_BLEND_OP_HSL_COLOR_EXT" },
                                            { VK_BLEND_OP_HSL_LUMINOSITY_EXT, "VK_BLEND_OP_HSL_LUMINOSITY_EXT" },
                                            { VK_BLEND_OP_PLUS_EXT, "VK_BLEND_OP_PLUS_EXT" },
                                            { VK_BLEND_OP_PLUS_CLAMPED_EXT, "VK_BLEND_OP_PLUS_CLAMPED_EXT" },
                                            { VK_BLEND_OP_PLUS_CLAMPED_ALPHA_EXT, "VK_BLEND_OP_PLUS_CLAMPED_ALPHA_EXT" },
                                            { VK_BLEND_OP_PLUS_DARKER_EXT, "VK_BLEND_OP_PLUS_DARKER_EXT" },
                                            { VK_BLEND_OP_MINUS_EXT, "VK_BLEND_OP_MINUS_EXT" },
                                            { VK_BLEND_OP_MINUS_CLAMPED_EXT, "VK_BLEND_OP_MINUS_CLAMPED_EXT" },
                                            { VK_BLEND_OP_CONTRAST_EXT, "VK_BLEND_OP_CONTRAST_EXT" },
                                            { VK_BLEND_OP_INVERT_OVG_EXT, "VK_BLEND_OP_INVERT_OVG_EXT" },
                                            { VK_BLEND_OP_RED_EXT, "VK_BLEND_OP_RED_EXT" },
                                            { VK_BLEND_OP_GREEN_EXT, "VK_BLEND_OP_GREEN_EXT" },
                                            { VK_BLEND_OP_BLUE_EXT, "VK_BLEND_OP_BLUE_EXT" },
                                        })

NLOHMANN_JSON_SERIALIZE_ENUM(VkDynamicState, {
                                                 { VK_DYNAMIC_STATE_VIEWPORT, "VK_DYNAMIC_STATE_VIEWPORT" },
                                                 { VK_DYNAMIC_STATE_SCISSOR, "VK_DYNAMIC_STATE_SCISSOR" },
                                                 { VK_DYNAMIC_STATE_LINE_WIDTH, "VK_DYNAMIC_STATE_LINE_WIDTH" },
                                                 { VK_DYNAMIC_STATE_DEPTH_BIAS, "VK_DYNAMIC_STATE_DEPTH_BIAS" },
                                                 { VK_DYNAMIC_STATE_BLEND_CONSTANTS, "VK_DYNAMIC_STATE_BLEND_CONSTANTS" },
                                                 { VK_DYNAMIC_STATE_DEPTH_BOUNDS, "VK_DYNAMIC_STATE_DEPTH_BOUNDS" },
                                                 { VK_DYNAMIC_STATE_STENCIL_COMPARE_MASK, "VK_DYNAMIC_STATE_STENCIL_COMPARE_MASK" },
                                                 { VK_DYNAMIC_STATE_STENCIL_WRITE_MASK, "VK_DYNAMIC_STATE_STENCIL_WRITE_MASK" },
                                                 { VK_DYNAMIC_STATE_STENCIL_REFERENCE, "VK_DYNAMIC_STATE_STENCIL_REFERENCE" },
                                                 { VK_DYNAMIC_STATE_CULL_MODE, "VK_DYNAMIC_STATE_CULL_MODE" },
                                                 { VK_DYNAMIC_STATE_FRONT_FACE, "VK_DYNAMIC_STATE_FRONT_FACE" },
                                                 { VK_DYNAMIC_STATE_PRIMITIVE_TOPOLOGY, "VK_DYNAMIC_STATE_PRIMITIVE_TOPOLOGY" },
                                                 { VK_DYNAMIC_STATE_VIEWPORT_WITH_COUNT, "VK_DYNAMIC_STATE_VIEWPORT_WITH_COUNT" },
                                                 { VK_DYNAMIC_STATE_SCISSOR_WITH_COUNT, "VK_DYNAMIC_STATE_SCISSOR_WITH_COUNT" },
                                                 { VK_DYNAMIC_STATE_VERTEX_INPUT_BINDING_STRIDE, "VK_DYNAMIC_STATE_VERTEX_INPUT_BINDING_STRIDE" },
                                                 { VK_DYNAMIC_STATE_DEPTH_TEST_ENABLE, "VK_DYNAMIC_STATE_DEPTH_TEST_ENABLE" },
                                                 { VK_DYNAMIC_STATE_DEPTH_WRITE_ENABLE, "VK_DYNAMIC_STATE_DEPTH_WRITE_ENABLE" },
                                                 { VK_DYNAMIC_STATE_DEPTH_COMPARE_OP, "VK_DYNAMIC_STATE_DEPTH_COMPARE_OP" },
                                                 { VK_DYNAMIC_STATE_DEPTH_BOUNDS_TEST_ENABLE, "VK_DYNAMIC_STATE_DEPTH_BOUNDS_TEST_ENABLE" },
                                                 { VK_DYNAMIC_STATE_STENCIL_TEST_ENABLE, "VK_DYNAMIC_STATE_STENCIL_TEST_ENABLE" },
                                                 { VK_DYNAMIC_STATE_STENCIL_OP, "VK_DYNAMIC_STATE_STENCIL_OP" },
                                                 { VK_DYNAMIC_STATE_RASTERIZER_DISCARD_ENABLE, "VK_DYNAMIC_STATE_RASTERIZER_DISCARD_ENABLE" },
                                                 { VK_DYNAMIC_STATE_DEPTH_BIAS_ENABLE, "VK_DYNAMIC_STATE_DEPTH_BIAS_ENABLE" },
                                                 { VK_DYNAMIC_STATE_PRIMITIVE_RESTART_ENABLE, "VK_DYNAMIC_STATE_PRIMITIVE_RESTART_ENABLE" },
                                             })

NLOHMANN_JSON_SERIALIZE_ENUM_FLAGS(VkSampleCountFlagBits, VkSampleCountFlags, {
                                                                                  { VK_SAMPLE_COUNT_1_BIT, "VK_SAMPLE_COUNT_1_BIT" },
                                                                                  { VK_SAMPLE_COUNT_2_BIT, "VK_SAMPLE_COUNT_2_BIT" },
                                                                                  { VK_SAMPLE_COUNT_4_BIT, "VK_SAMPLE_COUNT_4_BIT" },
                                                                                  { VK_SAMPLE_COUNT_8_BIT, "VK_SAMPLE_COUNT_8_BIT" },
                                                                                  { VK_SAMPLE_COUNT_16_BIT, "VK_SAMPLE_COUNT_16_BIT" },
                                                                                  { VK_SAMPLE_COUNT_32_BIT, "VK_SAMPLE_COUNT_32_BIT" },
                                                                                  { VK_SAMPLE_COUNT_64_BIT, "VK_SAMPLE_COUNT_64_BIT" },
                                                                              })

NLOHMANN_JSON_SERIALIZE_ENUM(VkFilter, {
                                           { VK_FILTER_NEAREST, "VK_FILTER_NEAREST" },
                                           { VK_FILTER_LINEAR, "VK_FILTER_LINEAR" },
                                       })

// NLOHMANN_JSON_SERIALIZE_ENUM_FLAGS(VkCullModeFlagBits, VkCullModeFlags, {
//     {VK_CULL_MODE_FRONT_BIT, "VK_CULL_MODE_FRONT_BIT"},
//     {VK_CULL_MODE_BACK_BIT, "VK_CULL_MODE_BACK_BIT"},
// })