#pragma once

#include "Math/Vector2.hpp"
#include "Window/Window.hpp"

#include <SDL2/SDL_keycode.h>


namespace bl {

enum class Key
{

// WINDOW EVENTS
    WindowResize,
    WindowMinimize,
    WindowMaximize,
    WindowClose,
    WindowMove,

    KeyUnknown = SDLK_UNKNOWN,
    KeyReturn = SDLK_RETURN,
    KeyEscape = SDLK_ESCAPE,
    KeyBackspace = SDLK_BACKSPACE,
    KeyTab = SDLK_TAB,
    KeySpace = SDLK_SPACE,
    KeyExclaim = SDLK_EXCLAIM,
    KeyQuoteDbl = SDLK_QUOTEDBL,
    KeyHash = SDLK_HASH,
    KeyPercent = SDLK_PERCENT,
    KeyDollar = SDLK_DOLLAR,
    KeyAmpersand = SDLK_AMPERSAND,
    KeyQuote = SDLK_QUOTE,
    KeyLeftParen = SDLK_LEFTPAREN,
    KeyRightParen = SDLK_RIGHTPAREN,
    KeyAsterisk = SDLK_ASTERISK,
    KeyPlus = SDLK_PLUS,
    KeyComma = SDLK_COMMA,
    KeyMinus = SDLK_MINUS,
    KeyPeriod = SDLK_PERIOD,
    KeySlash = SDLK_SLASH,
    Key0 = SDLK_0,
    Key1 = SDLK_1,
    Key2 = SDLK_2,
    Key3 = SDLK_3,
    Key4 = SDLK_4,
    Key5 = SDLK_5,
    Key6 = SDLK_6,
    Key7 = SDLK_7,
    Key8 = SDLK_8,
    Key9 = SDLK_9,
    KeyColon = SDLK_COLON,
    KeySemicolon = SDLK_SEMICOLON,
    KeyLess = SDLK_LESS,
    KeyEquals = SDLK_EQUALS,
    KeyGreater = SDLK_GREATER,
    KeyQuestion = SDLK_QUESTION,
    KeyAt = SDLK_AT,
    KeyLeftBracket = SDLK_LEFTBRACKET,
    KeyBackslash = SDLK_BACKSLASH,
    KeyRightBracket = SDLK_RIGHTBRACKET,
    KeyCaret = SDLK_CARET,
    KeyUnderscore = SDLK_UNDERSCORE,
    KeyBackquote = SDLK_BACKQUOTE,
    KeyA = SDLK_a,
    KeyB = SDLK_b,
    KeyC = SDLK_c,
    KeyD = SDLK_d,
    KeyE = SDLK_e,
    KeyF = SDLK_f,
    KeyG = SDLK_g,
    KeyH = SDLK_h,
    KeyI = SDLK_i,
    KeyJ = SDLK_j,
    KeyK = SDLK_k,
    KeyL = SDLK_l,
    KeyM = SDLK_m,
    KeyN = SDLK_n,
    KeyO = SDLK_o,
    KeyP = SDLK_p,
    KeyQ = SDLK_q,
    KeyR = SDLK_r,
    KeyS = SDLK_s,
    KeyT = SDLK_t,
    KeyU = SDLK_u,
    KeyV = SDLK_v,
    KeyW = SDLK_w,
    KeyX = SDLK_x,
    KeyY = SDLK_y,
    KeyZ = SDLK_z,
    KeyCapsLock = SDLK_CAPSLOCK,
    KeyF1 = SDLK_F1,
    KeyF2 = SDLK_F2,
    KeyF3 = SDLK_F3,
    KeyF4 = SDLK_F4,
    KeyF5 = SDLK_F5,
    KeyF6 = SDLK_F6,
    KeyF7 = SDLK_F7,
    KeyF8 = SDLK_F8,
    KeyF9 = SDLK_F9,
    KeyF10 = SDLK_F10,
    KeyF11 = SDLK_F11,
    KeyF12 = SDLK_F12,
    KeyPrintScreen = SDLK_PRINTSCREEN,
    KeyScrollLock = SDLK_SCROLLLOCK,
    KeyPause = SDLK_PAUSE,
    KeyInsert = SDLK_INSERT,
    KeyHome = SDLK_HOME,
    KeyPageUp = SDLK_PAGEUP,
    KeyDelete = SDLK_DELETE,
    KeyEnd = SDLK_END,
    KeyPageDown = SDLK_PAGEDOWN,
    KeyRight = SDLK_RIGHT,
    KeyLeft = SDLK_LEFT,
    KeyDown = SDLK_DOWN,
    KeyUp = SDLK_UP,
    KeyNumlockClear = SDLK_NUMLOCKCLEAR,
    KeyKpDivide = SDLK_KP_DIVIDE,
    KeyKpMultiply = SDLK_KP_MULTIPLY,
    KeyKpMinus = SDLK_KP_MINUS,
    KeyKpPlus = SDLK_KP_PLUS,
    KeyKpEnter = SDLK_KP_ENTER,
    KeyKp_1 = SDLK_KP_1,
    KeyKp_2 = SDLK_KP_2,
    KeyKp_3 = SDLK_KP_3,
    KeyKp_4 = SDLK_KP_4,
    KeyKp_5 = SDLK_KP_5,
    KeyKp_6 = SDLK_KP_6,
    KeyKp_7 = SDLK_KP_7,
    KeyKp_8 = SDLK_KP_8,
    KeyKp_9 = SDLK_KP_9,
    KeyKp_0 = SDLK_KP_0,
    KeyKpPeriod = SDLK_KP_PERIOD,
    KeyApplication = SDLK_APPLICATION,
    KeyPower = SDLK_POWER,
    KeyKpEquals = SDLK_KP_EQUALS,
    KeyF13 = SDLK_F13,
    KeyF14 = SDLK_F14,
    KeyF15 = SDLK_F15,
    KeyF16 = SDLK_F16,
    KeyF17 = SDLK_F17,
    KeyF18 = SDLK_F18,
    KeyF19 = SDLK_F19,
    KeyF20 = SDLK_F20,
    KeyF21 = SDLK_F21,
    KeyF22 = SDLK_F22,
    KeyF23 = SDLK_F23,
    KeyF24 = SDLK_F24,
    KeyExecute = SDLK_EXECUTE,
    KeyHelp = SDLK_HELP,
    KeyMenu = SDLK_MENU,
    KeySelect = SDLK_SELECT,
    KeyStop = SDLK_STOP,
    KeyAgain = SDLK_AGAIN,
    KeyUndo = SDLK_UNDO,
    KeyCut = SDLK_CUT,
    KeyCopy = SDLK_COPY,
    KeyPaste = SDLK_PASTE,
    KeyFind = SDLK_FIND,
    KeyMute = SDLK_MUTE,
    KeyVolumeUp = SDLK_VOLUMEUP,
    KeyVolumeDown = SDLK_VOLUMEDOWN,
    KeyKpComma = SDLK_KP_COMMA,
    KeyKpEqualSas400 = SDLK_KP_EQUALSAS400,
    KeyAltErase = SDLK_ALTERASE,
    KeySysReq = SDLK_SYSREQ,
    KeyCancel = SDLK_CANCEL,
    KeyClear = SDLK_CLEAR,
    KeyPrior = SDLK_PRIOR,
    KeyReturn2 = SDLK_RETURN2,
    KeySeparator = SDLK_SEPARATOR,
    KeyOut = SDLK_OUT,
    KeyOper = SDLK_OPER,
    KeyClearAgain = SDLK_CLEARAGAIN,
    KeyCrsel = SDLK_CRSEL,
    KeyExsel = SDLK_EXSEL,
    KeyKp_00 = SDLK_KP_00,
    KeyKp_000 = SDLK_KP_000,
    KeyThousandsSeparator = SDLK_THOUSANDSSEPARATOR,
    KeyDecimalSeparator = SDLK_DECIMALSEPARATOR,
    KeyCurrencyUnit = SDLK_CURRENCYUNIT,
    KeyCurrencySubUnit = SDLK_CURRENCYSUBUNIT,
    KeyKpLeftParen = SDLK_KP_LEFTPAREN,
    KeyKpRightParen = SDLK_KP_RIGHTPAREN,
    KeyKpLeftBrace = SDLK_KP_LEFTBRACE,
    KeyKpRightBrace = SDLK_KP_RIGHTBRACE,
    KeyKpTab = SDLK_KP_TAB,
    KeyKpBackspace = SDLK_KP_BACKSPACE,
    KeyKpA = SDLK_KP_A,
    KeyKpB = SDLK_KP_B,
    KeyKpC = SDLK_KP_C,
    KeyKpD = SDLK_KP_D,
    KeyKpE = SDLK_KP_E,
    KeyKpF = SDLK_KP_F,
    KeyKpXor = SDLK_KP_XOR,
    KeyKpPower = SDLK_KP_POWER,
    KeyKpPercent = SDLK_KP_PERCENT,
    KeyKpLess = SDLK_KP_LESS,
    KeyKpGreater = SDLK_KP_GREATER,
    KeyKpAmpersand = SDLK_KP_AMPERSAND,
    KeyKpDblAmpersand = SDLK_KP_DBLAMPERSAND,
    KeyKpVerticalBar = SDLK_KP_VERTICALBAR,
    KeyKpDblVerticalBar = SDLK_KP_DBLVERTICALBAR,
    KeyKpColon = SDLK_KP_COLON,
    KeyKpHash = SDLK_KP_HASH,
    KeyKpSpace = SDLK_KP_SPACE,
    KeyKpAt = SDLK_KP_AT,
    KeyKpExclam = SDLK_KP_EXCLAM,
    KeyKpMemStore = SDLK_KP_MEMSTORE,
    KeyKpMemRecall = SDLK_KP_MEMRECALL,
    KeyKpMemClear = SDLK_KP_MEMCLEAR,
    KeyKpMemAdd = SDLK_KP_MEMADD,
    KeyKpMemSubtract = SDLK_KP_MEMSUBTRACT,
    KeyKpMemMultiply = SDLK_KP_MEMMULTIPLY,
    KeyKpMemDivide = SDLK_KP_MEMDIVIDE,
    KeyKpPlusMinus = SDLK_KP_PLUSMINUS,
    KeyKpClear = SDLK_KP_CLEAR,
    KeyKpClearEntry = SDLK_KP_CLEARENTRY,
    KeyKpBinary = SDLK_KP_BINARY,
    KeyKpOctal = SDLK_KP_OCTAL,
    KeyKpDecimal = SDLK_KP_DECIMAL,
    KeyKpHexadecimal = SDLK_KP_HEXADECIMAL,
    KeyLCtrl = SDLK_LCTRL,
    KeyLShift = SDLK_LSHIFT,
    KeyLAlt = SDLK_LALT,
    KeyLGui = SDLK_LGUI,
    KeyRCtrl = SDLK_RCTRL,
    KeyRShift = SDLK_RSHIFT,
    KeyRAlt = SDLK_RALT,
    KeyRGui = SDLK_RGUI,
    KeyMode = SDLK_MODE,
    KeyAudioNext = SDLK_AUDIONEXT,
    KeyAudioPrev = SDLK_AUDIOPREV,
    KeyAudioStop = SDLK_AUDIOSTOP,
    KeyAudioPlay = SDLK_AUDIOPLAY,
    KeyAudioMute = SDLK_AUDIOMUTE,
    KeyMediaSelect = SDLK_MEDIASELECT,
    KeyWww = SDLK_WWW,
    KeyMail = SDLK_MAIL,
    KeyCalculator = SDLK_CALCULATOR,
    KeyComputer = SDLK_COMPUTER,
    KeyAcSearch = SDLK_AC_SEARCH,
    KeyAcHome = SDLK_AC_HOME,
    KeyAcBack = SDLK_AC_BACK,
    KeyAcForward = SDLK_AC_FORWARD,
    KeyAcStop = SDLK_AC_STOP,
    KeyAcRefresh = SDLK_AC_REFRESH,
    KeyAcBookmarks = SDLK_AC_BOOKMARKS,
    KeyBrightnessDown = SDLK_BRIGHTNESSDOWN,
    KeyBrightnessUp = SDLK_BRIGHTNESSUP,
    KeyDisplaySwitch = SDLK_DISPLAYSWITCH,
    KeyKbdIllumToggle = SDLK_KBDILLUMTOGGLE,
    KeyKbdIllumDown = SDLK_KBDILLUMDOWN,
    KeyKbdIllumUp = SDLK_KBDILLUMUP,
    KeyEject = SDLK_EJECT,
    KeySleep = SDLK_SLEEP,
    KeyApp1 = SDLK_APP1,
    KeyApp2 = SDLK_APP2,
    KeyAudioRewind = SDLK_AUDIOREWIND,
    KeyAudioFastForward = SDLK_AUDIOFASTFORWARD,
    KeySoftLeft = SDLK_SOFTLEFT,
    KeySoftRight = SDLK_SOFTRIGHT,
    KeyCall = SDLK_CALL,
    KeyEndCall = SDLK_ENDCALL,

// MOUSE
    MouseLeft,
    MouseRight,
    MouseMiddle,
    MouseSideFront,
    MouseSideBack,
    MouseYAxis,
    MouseXAxis,

// GAMEPAD
    GamepadA,
    GamepadB,
    GamepadX,
    GamepadY,
    GamepadLeftBumper,
    GamepadRightBumper,
    GamepadBack,
    GamepadStart,
    GamepadGuide,
    GamepadLeftThumb,
    GamepadRightThumb,
    GamepadDPadUp,
    GamepadDPadRight,
    GamepadDPadDown,
    GamepadDPadLeft,
    GamepadLeftThumbstickXAxis,
    GamepadLeftThumbstickYAxis,
    GamepadRightThumbstickXAxis,
    GamepadRightThumbstickYAxis,
};

enum class InputEvent {
    Released = SDL_RELEASED,
    Pressed = SDL_PRESSED,
};

} // namespace bl