
#ifndef BLUEMETAL_MATERIAL_API_H
#define BLUEMETAL_MATERIAL_API_H

#ifdef BLUEMETAL_MATERIAL_STATIC_DEFINE
#  define BLUEMETAL_MATERIAL_API
#  define BLUEMETAL_MATERIAL_NO_EXPORT
#else
#  ifndef BLUEMETAL_MATERIAL_API
#    ifdef BLMaterial_EXPORTS
        /* We are building this library */
#      define BLUEMETAL_MATERIAL_API 
#    else
        /* We are using this library */
#      define BLUEMETAL_MATERIAL_API 
#    endif
#  endif

#  ifndef BLUEMETAL_MATERIAL_NO_EXPORT
#    define BLUEMETAL_MATERIAL_NO_EXPORT 
#  endif
#endif

#ifndef BLUEMETAL_DEPRECATED
#  define BLUEMETAL_DEPRECATED __attribute__ ((__deprecated__))
#endif

#ifndef BLUEMETAL_DEPRECATED_EXPORT
#  define BLUEMETAL_DEPRECATED_EXPORT BLUEMETAL_MATERIAL_API BLUEMETAL_DEPRECATED
#endif

#ifndef BLUEMETAL_DEPRECATED_NO_EXPORT
#  define BLUEMETAL_DEPRECATED_NO_EXPORT BLUEMETAL_MATERIAL_NO_EXPORT BLUEMETAL_DEPRECATED
#endif

#if 0 /* DEFINE_NO_DEPRECATED */
#  ifndef BLUEMETAL_MATERIAL_NO_DEPRECATED
#    define BLUEMETAL_MATERIAL_NO_DEPRECATED
#  endif
#endif

#endif /* BLUEMETAL_MATERIAL_API_H */
